### ISSUE TITLE
[2주차] 비지니스 정책과 비지니스 조건에 대한 로직 처리는 어디서?

### ISSUE THREAD

**Issue by beng9re** [IDIOT-s/object-book-study#11]
책과 같이 할인 정책과 할인 조건이라는 것을 명시하고 있는데 
해당 관련 내용은 어디 레어어? 혹은 어디 클래스 혹은 어디 패키지에 작성을 선호하나요?

**Comment by yeongsik** [comment]
기존에는 그냥 서비스 레이어에서 서비스 클래스 안에서 처리했던 것 같아요. 오브젝트 책을 읽으면서 느낀 건 책처럼 엔티티 클래스 내 메서드로 처리해야 겠다라는 생각이 들었습니다.

관련 내용을 검색하다가 비즈니스 로직이 많아져서 엔티티가 비대해질 경우에 대한 내용도 찾게 되어 공유합니당 
해당 내용은 관심도 분리를 통해 관심도에 맞게 엔티티를 나눠서 처리한다는 내용입니다. 
http://jaynewho.com/post/45 

DDD랑 클린 아키텍쳐도 공부해야겠다라는 생각이 듭니당 😢

**Comment by ch200203** [comment]
저도 해당 부분은 당연히 비즈니스=서비스레이어 에서 해야한다고 생각했어요.

다만, 최근에 공부를 하면서 바뀐 생각은 객체를 하나의 인격체로 보고`객체가 직접 자신의 상태를 결정한다`는 원칙에서 생각해 볼 때, 
**도메인 객체(클래스)**에서 작성해 주면 괜찮지 않을까 라는 생각을 해보았습니다.

조금만 더 주체적으로 이야기하자면, 할인 정책의 경우 다양하게 변경될 가능성이 있어 서비스에서는 A라는 할인 정책, 조건을 주입하는 방식으로 작성해주면 변화에도 유연하게 대처 할 수 있을거라고 생각했어요.

@yeongsik 님의 `관심도 분리`에 대해서도 좋은 글이 있어 링크를 남깁니다.
https://mangkyu.tistory.com/165

**Comment by JHwan96** [comment]
위의 두분과 비슷하겠지만 저도 처음에는 서비스 레이어에 작성하면 될거같다고 생각했는데, 2장까지의 책의 내용을 토대로 생각해보면 객체가 자율성을 갖는 위치(도메인일..까요)에 작성하는 것이 좀 더 나아보이는듯 합니다.

**Comment by beng9re** [comment]
저는 이렇게 생각했습니다. 

비지니스의 정책과 조건에 대해선 하나의 바구니(엔터티객체)에 담을 수 없다고 생각 했어요 
그 이유는 실질적으로 할인 조건(쿠폰, 시즌세일..등)이라고 예시를 들면 다른 도메인간의 협력이 필연적으로 발생한다고 생각했습니다.

그렇다면 할인조건, 할인정책과 같은 도메인 객체를 만들고 @ch200203님의 말씀처럼 서비스 레이어에서 주입받고 
각각 엔터티 클래스에서 간의 협력을 진행하는게 적절해보였어요

저만의 결론이라고 하면 자기 주체적으로 관리과 되는 도메인 혹은 엔터티 클래스에서 처리하고 
주체적으로 관리가 안되는 (객체간 협력을 하는 객체)인 경우에는 별도에 도메인 클래스로 분리해주자 라고 결론을 내었습니다.
