### ISSUE TITLE
[2주차] 유연한 설계와 쉬운코드

### ISSUE THREAD

**Issue by ch200203** [IDIOT-s/object-book-study#12]
객체지향적으로 코드를 작성하다보면, 

도메인을 잘 이해하고 비즈니스 로직(비즈니스적인 사이드 이펙트)에 대해서 잘 아는 사람은 객체지향적으로 재사용성과 확장가능한 소스코드를 만들어 낼 수 있습니다. 이렇게 되면 추후에 어떤 요청이 들어와도 유연하게 대처 할 수 있습니다.

이렇게만 보면 당연히 객체지향적인 코드가 좋아보입니다.

다만, 이후에 해당 개발자가 다른 사람으로 변경된다면 어떨까요?
당장 급하게 변경이 필요한 경우에 비즈니스 클래스만 확인해서 한두줄만 고치면 될 문제라고 가정해봅시다.
극단적으로 생각해보자면 여러개로 추상화되고 분리된 클래스들의 영향도를 파악 후 변경하기, 관련된 하나의 서비스레이어의 메소드만 읽어나가면서 수정하면 되는 경우.

극단적인 경우만 놓고 보았지만 후자의 경우가 당장에는 더 좋아보입니다.
두가지의 장점만을 잘 살려서 사용하기 위해서는 어떻게하면 좋을까요?

혹시 이에 대해서 여러분들은 어떤 고민을 하고 계신지 궁금합니다~ :)

**Comment by JHwan96** [comment]
확실히 인원 교체가 자주 발생하는 곳이라면 후자가 가지는 이점이 전자보다 클 것 같습니다. 그렇지만 멀리 봤을 때, 서비스를 확장하거나 수정할 때 문제가 발생할 확률이 후자가 더 높지 않을까요?
둘 사이의 장점을 잘 살리는 방법은 아니지만, 전자의 방법에서 문서화를 제대로(자주) 한다면 어느정도 개발자들이 코드를 이해하기 위해 소모하는 비용을 줄일 수 있지 않을까 싶습니다 :)

> 다른 분들의 의견도 궁금하네요

**Comment by beng9re** [comment]
참 어려운 질문과 생각인거 같아요.

**관련된 하나의 서비스레이어의 메소드만 읽어나가면서 수정하면 되는 경우.**
> 이 케이스에는 절차지향으로 짜야 되지 않을까요? 

근데, 제가 서비스를 운영하다보면서 느낀 건데 특정 요구사항을 변경하는 입장에서 결론적으로는 "서비스레이어의 메소드만 수정하는 케이스" 나올수 있겠지만 이거를 도출하기 위한 과정(영향도 파악)에 들어가는 **시간**은 압도적으로 객체지향이 유리하다고 생각이 됩니다.

저희 특정 프로젝트는 슈퍼 모놀리식 절차지향이기 때문에 점점 어려움을 느끼고 있어요 실 코드 작성시간은 20분인데 영향도 파악만 몇 시간씩 걸립니다.

**두가지의 장점만을 잘 살려서 사용하기 위해서는 어떻게하면 좋을까요?**

* 코드리뷰로 보완이 가능할꺼 같습니다.
* 코드 작성의 문서화를 하면 좋겠네요? 이럴땐 절차지향, 객체지향써라 등과 같은 코드 작성 룰과 같은거요
* 극단적인 상황이면 핫픽스 같긴 한데 정말 그 부분만 수정하면 땡인지 다시 모여서 봐보고 검증해보고 개선코드점을 그 이후 배포에 포함 시킬꺼 같네요

**하하 근데, 제어가 안되는 외부 개발자인 경우에는 저도 어렵네요 ㅋㅋㅋㅋㅋㅋ  (도와주세요)**
