### ISSUE TITLE
[2주차] 다형성과 합성

### ISSUE THREAD

**Issue by platanus-kr** [IDIOT-s/object-book-study#13]
금주는 격주로 진행되지요. 책은 벌써 다 봤는데 리뷰를 올려볼려니 다시 한번 더 읽게되네요.

2장은 추상 클래스를 통한 상속과 인터페이스를 사용한 합성에 대한 내용이였습니다.

스프링으로 개발을 하게 되면 인터페이스의 구현이 대부분이고 추상 클래스에 대해서는 스프링이 내부적으로 알아서 처리해주는게 대부분이니 굳이 부모를 호출할 필요가 없는 경우가 대부분이죠. 실은 그래서 객체지향 개발자로 활동 하면서도 추상 클래스를 통한 상속을 할일이 없었어요. 이번에 **설계**라는 관점에서 왜 추상 클래스가 필요한건지 알게 됐습니다. 

또한 막연히 알고있는 '상속보다 인터페이스를 구현 해야한다' 는 주장에 대한 근거로 합성(인터페이스)를 통해 상속의 두가지 문제인 내부 구조 의존과 런타임 시점에 객체를 변경할 수 없다는 점을 해결할 수 있다는 것도 알게 됐습니다.

개인적으로는 'is-a'나 'has-a' 같은 식상한 이야기보다 코드가 예시로 나와줘서 그점이 참 좋았습니다.
이번장엔 따로 궁금한건 없었네요

그럼 금주도 수고 많으셨습니다.

**Comment by JHwan96** [comment]
금주도 고생 많으셨습니다!
혹시 `추상 클래스에 대해서는 스프링이 내부적으로 알아서 처리해주는게` 이부분 한번 기회가 되면 설명해주실 수 있으실까요ㅋ.ㅋ..
