### ISSUE TITLE
[3주차] 상태에 관한 ORM 모델링을 어떻게 해야 할까요?

### ISSUE THREAD

**Issue by platanus-kr** [IDIOT-s/object-book-study#14]
> 모델링을 할때 객체가 아니라 역할을 중점으로 생각하면 설계가 유연해진다.

3장 부터는 본격 설계와 관련된 이야기로 들어가네요. 이 말을 하기 위해서 같은 이야기가 계속해서 반복되는것 같았어요. 책에서는 추상화를 할때 "협력에 적합한 책임을 수행하는 대상이 한 종류라면 간단하게 객체로 간주한다. 여러종류의 객체들이 참여할 수 있다면 역할로 간주한다." 로 정리를 하고 있습니다.

또한 데이터 주도 설계에 관한 이야기가 나왔는데요. 상태를 중점으로 내부 구현에 초점을 맞추면 캡슐화를 저해하고 개별 객체들에 대한 응집도가 떨어진다는 내용이였습니다. 여기서 여러분들께 궁금한것이 있는데요. JPA같은 ORM으로 RDB 모델링을 할때 주로 엔티티의 상태를 가지고 설계하는게 일반적입니다. 만약 이 책의 내용대로 상태가 중점이 아닌 역할에 따른 도메인 분류로 설계한다면 엔티티 모델링을 어떻게 하는게 좋을까요..?

금주도 수고 많으셨습니다.

**Comment by beng9re** [comment]
> JPA같은 ORM으로 RDB 모델링을 할때 주로 엔티티의 상태를 가지고 설계하는게 일반적입니다. 만약 이 책의 내용대로 상태가 중점이 아닌 역할에 따른 도메인 분류로 설계한다면 엔티티 모델링을 어떻게 하는게 좋을까요?

저는 결론부터 말하자면 개인적으로 ORM 엔티티와 도메인 객체는 따로 분리되어 관리 되어야 한다는 입장입니다.

ORM 엔티티가 객체지향와 DB간의 불일치를 어느정도 해결하는걸로는 이해는 하지만, 
이미 ORM 엔티티는 DB간의 강한 의존을 가지고 있고 DB를 관리하는 책임이 이미 있다고 생각이 들어서요.
순수한 도메인 객체로 쓰기에는 나중에는 DB에 대한 어노테이션이 덕지덕지 붙는거 보면 저희가 말하는 도메인 객체와는 어울리지 않는다는게 제 입장입니다.

> JPA같은 ORM으로 RDB 모델링을 할때 주로 엔티티의 상태를 가지고 설계하는게 일반적입니다.
이부분은 트레이드 오프의 산물이라고 저는 개인적으로 생각합나다.
