### ISSUE TITLE
[2주차] 개체 != 클래스

### ISSUE THREAD

**Issue by unknownKade** [IDIOT-s/object-book-study#16]
객체라고 해도 클래스로 생각하게 되는 경향이 있는데 객체를 설계하고 클래스로 구현하는  예시가 잘 나왔다고 생각합니다. 실제로 프로젝트 만들면서 상속을 쓸 기회가 없었는데 2장 보고 생각해보니 그저 객체보다 클래스 구현만 생각하다 보니 상속을 안 한 것이었습니다. 꼭 상속으로 직접적이지 않은 의존이 좋은 것은 아니지만 규모 큰 프로젝트에는 좋은 접근이라고 생각합니다.

**Comment by JHwan96** [comment]
이번주도 고생 많으셨습니다 :)
혹시 `상속을 쓸 기회가 없었는데` 가 실제로 상속을 사용할 상황이 발생하지 않은 것인지, 아니면 상속 대신 다른 방법을 사용하는 것인지 궁금해서 질문드립니다~
