### ISSUE TITLE
[3주차] 객체의 행동과 상태의 차이

### ISSUE THREAD

**Issue by unknownKade** [IDIOT-s/object-book-study#17]
3장에서 다루어진 내용중 역할에서 객체의 상태가 아닌 행동에 집중해야한다고 강조하는데 둘의 차이가 명확하게 이해되지 않습니다. 이 부분(p85)에서 제기되는 문제는, 상태를 정하고 상태에 따라 동작하는 퍼블릭 인터페이스를 만드는 것이 캡슐화를 깬다고 합니다. 지금껏 나왔던 예시에서 메시지를 수신하는 퍼블릭 메소드들이 해당 경우가 아닌가요?

**Comment by ch200203** [comment]
먼저 객체의 상태, 와 행동에 차이에 대해서 제 생각을 말씀드리겠습니다.

객체의 상태는 객체가 어떤 데이터나 속성을 가지고 있는지를 나타냅니다.
보통 객체의 필드나 속성으로 표현되게 됩니다.

예를 들어 `자동차` 라는 객체가 있을 때 해당 객체의 상태는 `브랜드`, `모델`, `색상`, `최고 속도`, `연료량`. `속도` 등과 같은 데이터로 표현될 수 있는 값들을 의미합니다.

객체의 행동은 객체가 수행할 수 있는 작업을 의미합니다.
이는 메서드를 통해 표현 될 수 있다고 생각합니다.
예를 들어 `자동차` 객체에서는 `엑셀을 밟아 앞으로 전진한다.`, `브레이크를 밟아 감속한다.` `속도가 0이되면 정지한다.`와 같이 표현될 수 있습니다.

이러한 개념을 가지고 **상태가 아닌 행동에 집중한다.** 라는 말을 이해해보자면
캡슐화는 `객체의 상태를 외부로부터 숨기고, 객체의 행동만을 외부에 제공` 하는 것입니다.

`자동차` 가 움직이는 속도 값이 있다고 할 때, `속도`라는 필드값을  직접 조작 하는 것은 캡슐화를 깨는 행동입니다. 
(예를 들어 setter 메서드)
`속도` 라는 상태를 변경하기 위해서는 '엑셀을 밟아 전진' 하거나, '브레이크를 밟아 감속' 하는 행위를 통해서(메서드를 보내서) 상태값에 직접 접근하지 않고 행위를 통해 조작을 하여 상태를 보호 하고, 변경을 행동에 의존하는 것이 캡슐화를 유지하는 방법이라고 생각합니다.

모임시간에 책에서 보았던 구체적인 메서드를 언급해주시면 더 자세한 이야기 나눠볼 수 있을 것 같습니다.

3장 읽으시느라 고생많으셨습니다~

**Comment by yeongsik** [comment]
객체의 상태에 우선적으로 집중해서 개발을 하면 내부구현과 인터페이스를 구분하지 못해서 추후에 클라이언트에게도 영향을 주고 캡슐화도 안된다라고 이해했습니다. 그래서 우선 객체의 행동으로 결정될 인터페이스 혹은 퍼블릭 메서드를 정해놓고 시작해야한다고 이해했습니다.
