### ISSUE TITLE
[2주차] 정리

### ISSUE THREAD

**Issue by JHwan96** [IDIOT-s/object-book-study#19]
- 훌륭한 협력이 훌륭한 객체를 낳고 훌륭한 객체가 훌륭한 클래스를 생성한다는 부분에서 클래스가 객체를 추상화 한 것이라는 것만 알았을 뿐 설계할 때 있어서 어떤 것이 더 선행되어야 하는지 생각해본적은 없는 것 같습니다.
- 도메인의 뜻을 매번 햇갈려했는데 이번 장을 통해 도메인이 가지는 의미를 조금이나마 파악할 수 있었습니다
- 용어적인 면에서 메시지를 수신한다는 것이 생각보다 생소했는데, 가지고 있는 의미를 확인할 수 있어서 좋았습니다.
- 이번 장을 통해 용어가 가지는 의미를 좀 이해할 수 있는 시간이 되었습니다.

질문
- 상속과 합성 부분에서 합성이 정확하게 어떤 의미로 사용되었는지 궁금해서 설명해주실 멋진분 찾습니다~

**Comment by beng9re** [comment]
제가 이해한 바로는 합성은 구현은 없이 메시지만 정의 해놓기 때문에 캡슐화가 확보가 된다는점? 이라는 걸로 해석은 되는데 
질문의 의도가 이게 맞는지는 모르겠네여.
