### ISSUE TITLE
[3주차] 대체 어떻게 "행동"에 먼저 초점을 맞출 수 있을까요?

### ISSUE THREAD

**Issue by zinzoddari** [IDIOT-s/object-book-study#22]
객체지향 패러다임에 갓 입문한 사람들이 가장 쉽게 빠지는 것이 바로 객체의 "행동"이 아니라 "상태"에 초점이 맞춰진다는 것입니다.
상태를 먼저 정하고 그 후에 상태에 필요한 행위를 결정한다고 하는데, 아직까지 저도 "상태"를 먼저 구성을 하고 있는 것 같아요.

서비스를 구현할 때, 객체의 상태를 변경을 해야 하면 이전에는 생각없이 [ setter ]를 이용 해 주었던 것 같아요.
그리고, 나 이제 객체지향 쪼-끔 알잖아? 하고 바뀐 방법으로는 setter는 없애고 해당 객체에서 직접 상태를 바꿀 수 있도록, [ 캡슐화 ]를 해 주고 있는 것 같습니다.

근데, 이게 결국 상태가 먼저 정해졌고 이후 상태를 변경하는 행위를 작성하고 있다고 생각이 듭니다.
아직 연습이 덜 되기도 했고 새로운 부분이라 낯설어서 그렇겠지만, 과연 어떻게 "행동"을 먼저 초점을 맞추고 그 후에 "상태"를 고려해볼 수 있게되는걸까요? 

제가 사실 문맥을 제대로 이해했는지도 잘 모르겠네요 😂
한번 여러분들의 의견 들어보고 싶습니다 🙇🏻‍♀️

**Comment by ch200203** [comment]
사실 `상태`를 중심으로 객체를 설계하고 메서드를 작성하는 것은 저는 너무 당연하다고 생각합니다.

서비스를 구현할 때 새로운 객체를 만드는 일보다, 기존의 있는 객체를 가져와 쓰거나 조금씩 변경하여 기능을 추가하여 개발하는 일이 사실은 더 많다고 생각합니다.

그렇기 때문에 우리는 이미 정의 되어있는 객체의 상태를 마주하는 상황이 더 많다고 생각해요.

저는 도메인 객체를 볼 때, 객체의 필드변수부터 먼저 눈에 띄더라구요.

또한 우리가 기존에 코딩해왔던 방식은 상태에 집중하는 방식이었기 때문에 하루아침에 이를 버리기라는 쉽지 않다고 생각합니다.

되게 당연한 대답이고 특별한 대답은 아니지만, 행위를 바탕으로 상태를 추론하는 것을 연습해보는 방법 밖에는 없다고 생각합니다. (하지만, 실무는 도메인을 잘 아는 사람의 설계에 따라가는 것이 현실...)

결론 짓자면 제 생각은 "결국 상태가 먼저 정해졌고 이후 상태를 변경하는 행위를 작성하고 있다"가 잘못되었다고 저는 생각하지 않습니다.

먼저 상태를 바탕으로 설계 된 것에 행위를 바탕으로 리팩토링 하면 더 좋은 결과를 기대해 볼 수 있지 않을까요?
또, 그 과정을 도와주는 것은 결국 잘 작성된 테스트 코드라고 생각합니다.

**Comment by beng9re** [comment]
@ch200203 님 말씀처럼 

> 서비스를 구현할 때 새로운 객체를 만드는 일보다, 기존의 있는 객체를 가져와 쓰거나 조금씩 변경하여 기능을 추가하여 개발하는 일이 사실은 더 많다고 생각하기 때문입니다.

지나고 보니 저도 동감이네요. 대부분이 기존에 만든 코드들이 상태에 집중한 절차지향식코드만 바라보다보니 상태에 집중이 되는거 같고 
필요에 따라 상태만 추가하는 개발이 이루어진거 같아요.

저의 생각인데, 
 우리는 이미 행동을 통해 무언갈 만들고 있다고 생각해요 
도메인에 있어야할 행동들이 서비스레이어에 남겨지다 보니 행동들의 위치가 도메인객체는 행위가 빠지고 자연스럽게 상태만 관리하는 형태가 된거 같기도 해요. 

예를 들어, 주문하다라는 기능을 만들때 주문 컨트롤러 만들고 주문서비스에서 주문이라는(행동)을 만들고 어 그러면 데이터 뭐필요하냐 띡띡띡 도메인객체 짠 하고 나오는거 같습니다.

이 위치를 주문(도메인)객체에 주문하다라는(4장에서는 오퍼레이션 등장하기는 하더라구요.이라고) 이동해보고 생각해보면 이게 책에 쓰여진 행동을 중심으로 생각하는게 아닌지? 하는거 같아요

> 대체 어떻게 "행동"에 먼저 초점을 맞출 수 있을까요? 라는 질문에서는

2주차에 저희 토론때 나왔던 내용이긴 한데 Inside-Out 방식의 개발을 연습하다. 보면 어느정도 보완이 되지 않을까 합니다.
https://velog.io/@jhp1115/ATDD%EC%97%90%EC%84%9C-TDD-2%EC%A3%BC%EC%B0%A8#1-classical-tdd-inside-out

뭐 항상 나오는 말이지만 100%로 그렇게 짤필요는 없다고 생각합니다.
각 장단점이 있고 주어진 상황이 다르니까요
