### ISSUE TITLE
[4주차] 의존의 마지노선은 어디일까요?

### ISSUE THREAD

**Issue by platanus-kr** [IDIOT-s/object-book-study#23]
금주는 데이터 중심의 설계가 왜 설계 원칙에 위반되는지, 그 근거가 무엇인지에 대한 내용이였네요.
책에서 칭하는 절차지향이라고 부르는 코드들이 나와서 익숙한(?) 장이였습니다. 🫠

궁금한것 두가지 정도가 있는데 같이 생각해보면 좋을것 같아요.

1. 결합도와 응집도의 예시에서 서로 의존하고 있는 관계의 경우 메소드가 변경된다면 의존하는 쪽에서도 변경이 필요하다고 하죠. 이때 결합도와 응집도가 각각 받는 영향도가 정확하게 뭘까요..? 책에서는 결합도에 대해서는 '인터페이스가 아니라 구현을 변경하는 경우에도 의존하는 곳의 변경을 피할수 없으면 객체 사이의 결합도가 높다' 라고 하고 있고 응집도에 대해서는 '변경을 수용하기 위해서 코드의 여러곳을 동시에 변경해야 한다는 것이 설계의 응집도가 떨어진다' 라고 하는데요. 둘다 비슷한 말이 아닌가 싶어서요.
2. '의존'은 협력을 위해서 당연히 존재하는 부분이라고 생각하는데요, 캡슐화를 깨지 않으면서도 높은 응집도와 낮은 결합력을 가진 설계를 하기 위해서 프로그래밍 적으로 어떻게 설계를 해야할까요?

금주도 고생 많으셨습니다.

**Comment by yeongsik** [comment]
결합도는 하나의 객체가 영향을 주는 정도라고 생각을 했습니다. A라는 객체의 인터페이스를 B,C,D라는 객체에서 호출을 할 경우(메세지) A라는 객체의 인터페이스는 B,C,D 객체와 결합되어있다고 생각을 했습니다. 내부 구현과 외부 인터페이스의 구분이 잘 되어있지 않을 경우 변동 가능성이 높은 구현이 변경될 때마다 B,C,D에게 영향을 주는 상황이 되어버립니다. 

응집도는 책임이 분산되었는지, 책임의 하나의 객체에 응집되었는지에 대한 여부라고 생각했습니다. 하나의 기능 혹은 책임에 대해서 여러 객체에 그 책임이 분산되었을 때, 해당 기능을 수정할 때 여러 군데에서 수정을 해야 합니다. 

하나의 책임에 대해 객체에 응집도 높게 설계를 했더라도 해당 객체의 내부 구현과 퍼블릭 인터페이스의 구분을 잘 하지 못했을 경우 결합도가 높을 수도 있다는 생각이 듭니다.

4장을 읽고서 결합도는 객체의 캡슐화와 객체의 협력에 적절한 책임 분배에 따라 결정되는 것 같고, 응집도는 하나의 책임이 분산되지 않고, 알맞은 객체에 설정되는 것에 결정되는 것으로 이해했습니다.

**Comment by zinzoddari** [comment]
최근 책을 읽고 있는데 비슷한 단어가 계속 반복되어서 나오다 보니, 제가 문해력이 부족한건지 이해가 조금 어렵더라구요.
질문도 여러번 곱씹다가 조심스레 달아봅니다. 

서로 협력하고 있는 관계에서 인터페이스의 내부 구현이 바뀌게 되면서, 필요로 하는 파라미터가 추가 되었을 때. 이 때 의존하는 곳에서의 수정이 필요하게 되면서 서로가 점점 결합도가 높아지게 되는 것 같습니다. 서로가 서로한테 엮이는 부분이 많을 수록 나중에 떼어내기 어려워지고 흔히 말하는 레거시 덩어리가 되는게 아닐까? 싶습니다.

내부 구현이 바뀌고, 파라미터를 추가로 요하게 되면서 해당 인터페이스의 내부 구현에서 하는 일이 많아지고 결국 응집도가 높아진다의 예시가 되는 것 같습니다. 

그래서 응집도, 결합도를 낮추기 위함으로 책에서 말해주는게 캡슐화를 뜻한다. 정도로 저는 정리를 해 보았습니다.

2번의 경우, 저도 항상 고민이 많습니다. 컨트롤러에서 DTO를 서비스에 넘겨주고, 서비스에서 도메인으로 메세지를 전달 할 때,
정말 필요로하는 "값"만을 전달할지, 아니면 DTO 그대로를 전달해줘서 도메인 내부에서 값을 가져와서 사용할지 뭐가 맞을지 매번 고민하게 되는데요.
DTO를 그대로 전달하게 되면, 내부 구현 구현만 바뀌게 되어 결합도를 낮출 수 있다고 생각이 듭니다. 하지만, 과연 좋은 응집도를 가지고 있는걸까? 의문이 들게 되고,
서비스에서 DTO의 값을 꺼내 도메인으로 전달하게 되면, 값이 추가로 바뀌게 될 때는 결국 결합도가 올라가게 되는 것 같습니다.

결국, 내가 만들고자하는 인터페이스의 정확한 방향을 고려해서 최소한의 작업만을 처리하게 만든다면 수정의 가능성이 적어지지 않을까? 싶지만 아직 어려운 것 같네요 😂

정말 많이 고민하고 코멘트 달아보는데, 궁금하셨던 내용에 관한 대답이 맞을지도 잘 모르겠네요 💦

**Comment by platanus-kr** [comment]
@jinho-yoo-jack :  결국은 객체지향과 SOLID둘만의 이론으로는 불가능하고 결국은 디자인 패턴이라는 약속이 있어야 합의가 가능하다.이론과 경험, 이론과 실무는 다르다.
@midcondria : 앞장에서 나왔던 이야기와 상충된다. 이걸 해결하기 위해서 추상화를 해버리면 유연하긴 하지만 읽기가 어려워지고 상태에 종속되면 읽기는 쉬우나 수정이 매우 어려워진다.
