### ISSUE TITLE
[4주차] 후기

### ISSUE THREAD

**Issue by yeongsik** [IDIOT-s/object-book-study#24]
객체지향 설계에 대해 포문을 열었던 3장에 이어서 조금 더 자세히 객체지향 설계를 어떤 방법으로 해야하는지에 대해서 4장은 설명하고 있습니다. 
이번 장에서도 역시 책임을 강조하면서 이해하기 쉽게 데이터 주도 설계 예시 코드와 조금 더 구체적인 개념들(캡슐화, 응집도, 결합도)을 통해 객체지향 설계를 친절하게 설명해주었습니다.

지난 3장을 읽고 이야기 한 후 정리되었던 객체의 데이터에 집중하기보다는 협력, 객체들의 책임을 먼저 생각해서 설계를 해보자라는 생각이 4장을 읽으면서 좀 더 명확해졌습니다. 

인상깊었던 점은 캡슐화는 단순히 내부 데이터만 보여주지 않은 것이 아니라 변경될 만한 모든 것을 감추는 개념이라는 부분이었습니다. 

P.S : public getter 역시 캡슐화를 깬다는 내용이 책에서 나오는데 그럼 lombok의 @getter를 우리는 지양해야하는 걸까요?

**Comment by platanus-kr** [comment]
책에 따르면.. 그렇죠. 책에서 여러 이유를 설명하는것과 더불어서 개인적으로 `@Getter`를 지양해야 하는 이유는 코드 레벨에서 '해당 메소드를 어디서 호출하는지 추적이 안되기 때문' 이라고 생각합니다.

**Comment by zinzoddari** [comment]
getter 메소드를 쓰겠다는 것 자체가, "값을 가져와 활용을 하겠음"을 의미하는 것 같은데 
해당 값이 어디서 어떻게 쓰이는지, 민철님이 말씀하신대로 추적도 힘들것이고...
또 값을 꺼낸 순간, 해당 위치에서 "잘못된 책임의 로직"이 생길 위험도 있을것 같단 생각도 지금 쓰다보니 생각이 나네요.

아예 getter를 사용하지 않음은 다른 객체와의 협력을 위해서는 최소한의 사용은 필요하지 않나 봅니다.
대신 잘못된 책임이 생기지 않도록 유의하면서 코드 작성을 해야 할 것 같습니다.

**Comment by zinzoddari** [comment]
추가로 생각나서 얘기를 덧붙이자면, lombok으로 모든 필드에 대한 getter를 만드는게 답은 아닌 것 같아요.
정말 외부에 값을 제공을 해줘야하는 필드만에 getter 메서드를 직접 만들어 주는게 더 좋지 않을까? 싶습니다.
