### ISSUE TITLE
[4주차] p98 ~ p99에서의 인터페이스라는 용어는 퍼블릭 인터페이스를 뜻하는가?

### ISSUE THREAD

**Issue by beng9re** [IDIOT-s/object-book-study#25]
읽으면 읽을수록 인터페이스라는 용어가 Java의 interface 키워드를 가진 인터페이스를 말하는건지 퍼블릭 인터페이스를 말하는건지 
인지부조화가 생겨서 아무래도 퍼블릭 인터페이스를 의미하는게 맞겠죠?

**Comment by yeongsik** [comment]
저도 많이 헷갈렸는데 자바 인터페이스도 의미하고, 클래스의 public 메서드도 인터페이스라고 이해하면서 읽었습니다.
외부에서 메세지를 보낼 수 있는 것? 으로 이해하면 되지 않을까여?

**Comment by zinzoddari** [comment]
사실 저도 그놈의 인터페이스가 뭘까 싶었지만... 저번주 현우님이 말씀 주셨던 인터페이스 설명을 듣고, 책을 읽으니까 조금 헷갈림이 덜 했었어요.
영식님이 코멘트 달아주신 것 처럼, 저도 두가지가 결국 같은 의미를 뜻한다고 생각이 들었습니다.

외부에서 요청이오면, 어떠한 행위를 해서 값을 응답한다. 가 결국 인터페이스를 정리하는 말이 되는것 같습니다!

**Comment by platanus-kr** [comment]
저는 언어 스팩에 국한되는 의미라기 보다 메시지를 주고 받는 출입구라고 생각했어요. 자바로 따지면.. 클래스 내의 메소드 시그니처 정도인것 같아요. "의존관계"를 기준으로 캡슐화, 응집도, 결합도를 설명하기 좋은 용어를 찾으려고 범용적인 단어를 선택하신것 같다는 생각이 듭니다.

**Comment by beng9re** [comment]
모두들 같은 마음의 용어로 받아 주셨군요 

> 상태를 객체 분할의 중심축으 로 삼으면 구현에 관한 세부사항이 객체의 인터페이스에 스며들게 되어 캡슐화의 원칙이 무너진다. 결 과적으로 상태 변경은 인터페이스의 변경을 초래하며 이 인터페이스에 의존하는 모든 객체에게 변경의 영향이 퍼지게 된다. 따라서 데이터에 초점을 맞추는 설계는 변경에 취약할 수밖에 없다.

해당 문장속에서의 의미가 제가 생각 한 `퍼블릭 인터페이스`를 인터페이스라는 용어로 축약해서 적으신건가 했던거 였어요

찾다보니 p181 용어가 나와있군여 
> 퍼블릭 인터페이스: 객체가 협력에 참여하기 위해 외부에서 수신할 수 있는 메시지의 묶음. 클래스의 퍼블릭 메서드들 의 집합이나 메시지의 집합을 가리키는 데 사용된다. 객체를 설계할 때 가장 중요한 것은 훌륭한 퍼블릭 인터페이스를 설계하는 것이다.

더 찾다보니 향로님 글도 보여서 공유 드려요 
https://jojoldu.tistory.com/588

**Comment by ch200203** [comment]
해당 내용은 저자의 다른 저서인 '객체지향의 사실과 오해' 라는 책에서 해당 내용에 대해서 좀 더 알기 쉽게 설명 되어있더라구요

> 객체는 **외부**와 **내부**로 구성되어 있다.
> 객체의 외부와 내부를 명확하게 분리하는 것이 중요하다.
> 이때, 객체의 외부를 공용 인터페이스라고 부른다. ( 다른 객체에 노출되어 있는 부분 )
> 객체의 내부 구조와 작동방식을 가리키는 것이 구현 (Implementation)이다.

라고 설명이 되어있더라구요.

(는 적는 중에 명확한 설명을 찾으셨네요... 혹시 몰라서 남깁니다.)
