### ISSUE TITLE
[4주차] 후기

### ISSUE THREAD

**Issue by JHwan96** [IDIOT-s/object-book-study#26]
- 데이터 주도 설계를 하면 어떤 코드가 나오는지 예시와 캡슐화, 응집도, 결합도의 개념에 대해서 자세히 설명했습니다.
- 응집도, 결합도, 캡슐화라는 각 단어들의 개념에 대해서 잘 배울 수 있어서 좋았습니다.
- 캡슐화가 객체 내부의 데이터를 외부로부터 감추는 것 외에도 변할 수 있는 어떤 것이라도 감추는 것이라는 점이라는 것을 알게 되었습니다.

질문
1. 높은 결합도와 낮은 응집도에 대한 설명이 유사하다고 느껴졌는데 어떤 차이가 있는지 궁금합니다 :)
2. 인터페이스와 구현이라는 개념에서
  - 구현이 인터페이스의 구체화된 것인지 아니면 
  - 인터페이스와 구현(상태)이 아예 별개의 개념으로 봐야하는지 궁금합니다 
    - ex) 인터페이스는 메서드, 구현은 상태

**Comment by platanus-kr** [comment]
1은 제 질문 댓글에 @yeongsik 님과 @zinzoddari 님이 멋지게 작성해주신게 있어서 그걸로 대신 답변드립니다

2는 전자도 맞고 후자도 맞다고 생각하는데요. 개인적인 생각으로는 메시지를 주고받을때 우리가 자바스프링에서 다른 메소드에 메시지를 전달할때 맴버(int, String.. 등등)아닌 DTO(객체)를 쓴다는 개념이 책 진도상 등장하지 않았거나 아에 책에서 다루지 않을지도 모른다고 생각해요. 그래서 필요한 인자(메소드에서 필요로 하는 파라미터)가 인터페이스에 종속되어 변경에 취약해지고, 인터페이스에 맴버가 노출된다는 말을 하고 싶었던것 같습니다.

**Comment by beng9re** [comment]
1. 높은 결합도와 낮은 응집도의 차이 
* 높은 결합도
   - 외부모듈의 요소를 많이 가지고 있는가? 
   =>  다른 친구들의 협력이 많은 상태라고 생각이 들었어요 외부 책임을 수정하면 자기 자신도 변경이 이루어 진다 라고 생각이 들구요 
  
* 낮은 응집도 
    - 책임이 한곳(하나의 모듈)으로 모여 있는가?
    => 내 자신이 변화되면 외부 친구들에게 변화가 많이 이루어지는가로 생각이 됩니다.

제가 이해한바로는 이런데 적절할까요?

2. 인터페이스와 구현의 차이?
저는 인터페이스와 구현을 책임과 상태로 구별을 하고 있지는 않고 
추상화의 관점으로 이해를 했습니다,
추상화 한 것이 인터페이스고 추상화 한것을 구현한게 구현이라고 생각을 했습니다.

**Comment by JHwan96** [comment]
다른 분들이 쓰신 이슈들과 답변들 보면서 어느정도 많이 이해된듯합니다 다들 감사합니다 :)
