### ISSUE TITLE
[4주차]후기

### ISSUE THREAD

**Issue by unknownKade** [IDIOT-s/object-book-study#27]
데이터 중심 설계와의 차이점을 보여주면서 응집도와 결합도로 설명이 붙으니까 좀 더 이해하기 수월했습니다.
오히려 3장에서 했던 책임 중심으로 설계해서 객체들이 협력하는 것을 4장에서 이해가 되는 것 같아 속 뚫렸습니다.
저번 주에 토론했던 캡슐화 위반에 대해서도 좀 더 자세히 나와서 다시 생각을 정리해볼 기회가 되었습니다.
결과적으로는 협력을 할 수 밖에 없는데 완전한 은닉은 없다고 생각합니다. 캡슐화는 접근이 안되게 아예 막는다고 생각하게 되었는데 중요한 것은 내부 속성이 감춰지는 것입니다.

**Comment by zinzoddari** [comment]
오 맞아요 어쨌든 서로 협력은 하되, 최대한의 캡슐화를 통해서 결국 낮은 결합도와 높은 응집도를 갖도록 만드는것이 우리가 해야하는 객체지향적 코드 작성이지 않을까? 라는 생각이 들었습니다!

 ~ 완전한 은닉은 없다 ~ 좋은 말인 것 같네여 ㅎㅎㅋㅎㅋ
