### ISSUE TITLE
[4주차] 저는 정말 객체지향적으로 코드를 작성을 하고 있는걸까요?

### ISSUE THREAD

**Issue by zinzoddari** [IDIOT-s/object-book-study#28]
초반에 나왔던 내용 중 상태에 초점... 행동에 초점... 무슨 말인지 사실 아직 잘 와닿지가 않는 것 같습니다.
코드를 봐도 이것도 맞는 것 같고~ 저것도 맞는것 같고~ 
```상태에 초점```을 맞추게 되면, ```독립된 데이터 덩어리```... ```행동에 초점```을 두게 되면 ```협력하는 공동체의 일원```?

무슨 말인지도 잘 이해가 안되는 와중에, 과연 나는 ```객체지향```적으로 코드를 작성하고 있는걸까? 고민이 들었습니다.
캡슐화를 하는 것이 좋고, 한 쪽을 수정을 하더라도 다른 쪽에 영향이 최소한으로 가게끔- 나름 배웠던 내용을 인지하고 코드를 작성을 하고 있는데,
그렇다고하여 이것을 협력하는 공동체 처럼 인식을하고 있는 것인가? 라고 되물어도 잘 모르겠네요.

약간 어릴 떄 이해하고 수학을 푼 것이 아닌, 그냥 공식을 외워서 작성하는 수준이 지금도 그런 것 같다?
연습이 좀 더 필요한걸까요? 😂

이번 한 장을 한 줄로 설명하기 좋은 문장이 있던 것 같아 공유해봅니다.
[ 객체지향 설계 ]란, 올바른 객체에게 올바른 책임을 할당. 즉, 책임을 통해서 내부 구현을 ```캡슐화```해주고, 이를 통해 ```낮은 결합도``` 및 ```높은 응집도```를 가진 구조를 창조하는 활동이라고 합니다.

다들 고생하셨습니당

**Comment by midcondria** [comment]
사실 이게 그림들이랑 코드랑 보면서 해야 이해가 쉬운거 같아요
안그러면 내가 난독증인가? 하는 생각 5만배 들더라구요 :rage: 
![image](https://github.com/IDIOT-s/object-book-study/assets/119824778/d8613e6b-8e65-4d7e-b503-b60751112c61)
그림으로 차이가 느껴지실지 모르겠지만 제 생각엔 두개 차이가 
행동에 초점 - 앞 주차에서 했던 설계 단계에서부터 협력관계를 설정 -> 메시지(협력과정에서 필요한 행동)가 객체를 선택하고 이후 객체의 상태를 설정한다
vs
상태에 초점 - 이번 주차에서 했던것 처럼 우선 메서드 이런거 생각 안하고 먼저 객체가 가질 필드부터 주르륵 나열하고 getter, setter 로 데이터를 건드려서 원하는 기능을 구현하는것
이라는 생각이 드네요. 아님말고
