### ISSUE TITLE
[4주차] 4주차 후기

### ISSUE THREAD

**Issue by ch200203** [IDIOT-s/object-book-study#29]
개인적으로 3장에서의 내용을 보강하기 위한 챕터이지 않았나 싶습니다.

우리가 능동적이고 자율적인 객체를 설계하기 위해서는 `책임`을 중심으로 설계해야 하고 
그것이 `상태`를 중심으로 하는 기존의 설계 방법과 어떻게 다른지 비교하는 내용들이 많아 좋았습니다.

특히, 객체지향 설계에서 빠지지 않고 등장하는 개념인 **캡슐화**의 중요성에 대해 다시 한번 느낄 수 있었는데요.
우리가 좋은 코드라 부를 수 있는 코드는 결국 **유지보수성이 용이한 코드**라고 생각합니다.

그것을 도와주는 가장 큰 원칙이 캡슐화임을 여러번 깨닫게 해주었습니다.
대부분의 코드가 평소에 자주 보던 형태의 코드라 읽으면서 정말 양심에 많이 찔렸습니다.

유지보수성이 높고 객체지향적인 코드를 짜기 위해서 책임, 행동 등 어떤 것 부터 고려해야 할지 잘 모르겠다면 
먼저 캡슐화가 잘 되어있는지 확인하는 방법도 좋을 것 같습니다.

**Comment by zinzoddari** [comment]
혹시 이전에 철환님이 굳이 캡슐화를 하지 않고, 서비스 계층에 작성하는 편이 더 나을 수도 있지 않을까? 라는 말 기억나시나요?

저는 이번 장을 보면서 그 말이 좀 생각이 났는데,
결국 우리가 주로 개발하는 것은 스프링 웹 계층에서 크게 벗어나지 못하기에 이러한 생각이 든게 아닌가 싶습니다.

웹 개발이 아닌 정말 객체로 이루어진 개발을 한다면 객체 밖에서 드러나는 행위는 생길 수 없단 생각이 들었네요.

저도 이번에 내린 결론이 객체지향 시작의 첫 걸음은 캡슐화이지 않을까 싶습니다
캡슐화를 챙기게되면 자연스레 책임과 행동들이 나뉘게 되는 것 같아요.
헉 그럼 상태가 아닌 행위에 초점을 맞추는 설계가 맞는건가요..? 😳
아직도 상태 초점, 행위 초점 ㅜㅜㅜㅜㅜ 이해가 안되어서 쓰다가 머리 싸매고 있게 되네요 효효

**Comment by ch200203** [comment]
음 제가 말씀드리려고 했던 부분은

"객체로 이루어진 개발이 정말 효율적일까?" 라는 의견을 드리고 싶었습니다

사실 4장의 내용과 맞닿아 있는 내용이지 않을까 싶은데요. 
객체지향이 정말 우리에게 필요할까? => 그렇다면 왜? => 다른 방법들과 비교해서 뭐가 좋을지? 에 대해서 이야기를 나누고 싶었어요!
더 나아가서 이야기 드리고 싶었던건 주입 받은대로 혹은 정해진대로만 코딩하는것이 아니라 필요하다면 객체지향의 개념을 또 필요하다면 다른 개념을 주어진 문제상황에 맞게 해결할 수 있게 함께 다른상황도 생각해 보고 싶었습니다!

아침에 마침 코드 분석할 일이 있어서 테이블을 보다가 문득 생각이 드는데 
그럼 실제 사용테이블이 4천, 5천개가 넘어가는 시스템의 경우에는 테이블을 엔티티와 매핑하고 객체를 캡슐화하여 설계하고 구현 것...이 정말 효율적이고 좋은 방법일까요?
