### ISSUE TITLE
[1주차] 읽으면서 기록했던 부분 공유해보기

### ISSUE THREAD

**Issue by zinzoddari** [IDIOT-s/object-book-study#3]
안녕하세요 😃
제가 처음으로 글을 올리게 될 것 같아 상당히 부담스러운데요...
저도 어떻게 써야할지 모르겠지만 첫 시작을 끊어볼까 싶습니다.
이후에 올리시는 분들도 제가 쓴 형식 말고도 자유롭게 써주시면 좋을 것 같아요.

사실 첫장은 좀 가벼운 마음으로 봐서 그런지 저는 궁금한 점은 없었고, 항상 [ 단어 ]의 정의가 헷갈리는 편이기 때문에
이 위주로 기록을 남기면서 책을 봤습니다. 기록을 남긴걸 같이 공유하면서 정리해보면 좋지 않을까 싶어 해당 내용으로 올려볼까 합니다 🫡

``모듈``이란, 크기 상관 없이 클래스나 패키지, 라이브러리와 같이 프로그램을 구성하는 임의의 요소를 의미한다고 합니다.
모듈의 목적은 크게 3가지로
1. 실행 될 때 제대로 동작하기
2. 변경을 위해 존재하는 것
3. 코드를 읽는 사람과 의사소통을 하는 것
으로, 프로세스가 동일한 모듈 내부에 위치하도록 프로그래밍 하는 방식을 즉, [ ``객체지향 프로그래밍`` ]이라고 한다 합니다.

사실 이렇게만 하면, 모듈이 무엇인지 크게 잘 와닿지 않고, 그래서 객체지향 프로그래밍이 뭔데?! 싶었습니다 😥

저는 당장 1년 전까지만 해도, service 계층에 모든 로직을 다 넣어주고 또 별도 테스트 코드도 모르던 아직 머리가 덜 깨진 개발자 였는데요...🤣
설계를 어렵게 하는 것은 [ 의존성 ] 때문이고, 이를 해결하기 위해서는 객체 사이의 결합도(=의존도)를 낮추면 된다고 합니다.
생각해보면, 하나의 서비스안에 여러 개의 repository 심하면 같은 service 계층과의 관계를 맺고 로직을 구구절절로 짰기에
다른 피쳐 개발을 하다 해당 부분을 다시 보면 또 분석하는데에 시간이 오래 걸리기도 했고, 또 테스트도 잘 되지 못했던 것 같습니다.

그래서 지금도 그렇게 코드를 짜고 있냐고 물어보면, 객체 스스로가 뭔가 처리를 할 수 있다! 싶으면 객체 내부에 로직을 작성을 해 주고 있습니다.
이것을 통해객체 스스로가 책임을 강하게 갖게 되고, 자연스럽게 의존도가 낮아지며 코드가 간결해지고, 또 단위 테스트에도 용이하게 된 것 같습니다. 
객체 내부에 로직 작성을 [ 캡슐화 ] 라고 할 수 있다고 합니다.

외부에서 해당 객체에 필요한 것을 요구(메시지)를 하게 되면, 객체 내부에서 어떻게든 처리해 내가 원한 메시지의 응답을 받는 것을 보장해 주는 것이 
결국 최소한의 의존성을 제외하고 객체간 협력을 할 수 있는 것을 [ ``객체지향 설계`` ]를 뜻한다고 합니다.

설계를 보니 위의 모듈과 함께 설명 했던 [ 객체지향 프로그래밍 ]이 조금은 와닿았던 것 같습니다.

책의 앞에 이론보단 실무가 먼저이고 실무로 다진 기반들이 모여 이후에 이론으로 정립이 되었다고 하는데, 확실히 글로만 읽는 것 보단 직접 이렇게 코드를 짜고 있는 상태에서 책을 다시 봐보니 몸소 느껴지는 바가 다른 것 같습니다. 다른 분들도 책을 읽으면서 어느 부분이 기억에 남는지 궁금하기에 빨리 첫주 모임을 가지고 싶단 생각이 듭니다 😄 

감사합니다 ~ ~

p.s. 다들 책 읽으실 때, 좋은 부분은 바로바로 남기면서 읽는 편인지,
혹은 마지막 다 읽고나서 좋았던 점을 기억해서 남기는 편인지 궁금합니다. 🫠

**Comment by jinho-yoo-jack** [comment]
너무 좋은 것 같습니당ㅎㅎ
저는 좋았던 점이나 알게된 점은 밑줄과 형광색 및 별표3개로 마무리 후, 블로그에 정리하는 것 같습니다.

**Comment by Jwhyee** [comment]
책을 읽고 공감되고, 좋았던 부분을 정리하는게 정말 좋은 것 같아요!!
저는 따로 좋았던 점에 대해서는 정리하지 않지만, 이렇게 회고하면 머리에 더 오래 남을 것 같네요!
좋은 습관 하나 얻어갑니다,,

> 하나의 서비스안에 여러 개의 repository 심하면 같은 service 계층과의 관계를 맺고 로직을 구구절절로 짰기에

지금의 제 모습 같아 반성하게 되네요🤣🥲😂

**Comment by platanus-kr** [comment]
현업의 유즈케이스만 그대로 두고 개발을 했을때 저도 항상 예제와 같은 코드가 나오는데
변경이 어려운 코드에 대해서 저도 공감이 많이 됐습니다.
적절한 분리를 통해 협력을 한다는 의미가 무엇인지 알수 있었네요.

**Comment by beng9re** [comment]
그때 그때 다르지만 읽으면서 주요 키워드들을 하이라이팅 하고 요번에 처음 시도하는 거지만 ebook에 형광펜으로 칠해두고 형광펜의 주변 내용을 정리하는 편입니다
