### ISSUE TITLE
[4주차] 높은 응집도가 무조건 좋은걸까요?

### ISSUE THREAD

**Issue by zinzoddari** [IDIOT-s/object-book-study#31]
갑자기 궁금해졌습니다...
낮은 응집도의 경우 적절한 책임을 못지고 있을 수 있단 생각이 드는데
반대로 높은 응집도는 너무 많은 책임을 지고 있을 수도 있단 생각이 들었어요.

이거에 대한 다른분들의 의견도 궁금합니다 🙋🏻‍♀️

**Comment by platanus-kr** [comment]
그 경우 반대로 결합도가 올라가지 않을까요?

책임을 지고 있다는 것은 한 개의 책임만 몰리는게 아니라 (말이 이상하긴 한데 이 경우는 정상이죠?) 여러개의 책임이 한 객체에 있는것이고, 또 여러개의 책임이 몰리니까 의존하는 객체가 많아지고 결합도가 올라갈것 같다는 생각입니다.

> 변경 관점에서 결합도란 **한 모듈이 변경되기 위해서 다른 모듈의 변경을 요구하는 정도**로 측정할 수 있다. 하나의 모듈을 수정할 때 얼마나 많은 모듈을 함께 수정해야 하는지를 나타낸다. 결합도가 높을수록 함께 변경해야 하는 모듈의 수가 늘어나기 때문에 변경하기가 어려워진다.

**Comment by yeongsik** [comment]
유지보수 측면에서 높은 응집도가 저는 좋다고 생각합니다. 높은 응집도를 구현하려고 너무 많은 책임을 하나의 객체에 지고 있다면 책임을 좀 나눌 것 같아요. 응집도는 개발자가 설계한 책임,기능에 대한 응집도라고 생각이 들어서, 너무 많은 책임을 갖고 있다는 생각이 들 때는 해당 책임을 쪼갤 것 같습니다.

**Comment by midcondria** [comment]
설계란 변경을 위해 존재하며 합리적인 비용으로 변경을 수용하는 구조를 만드는거라면, 객체가 과도한 책임을 져서 변경 포인트가 많아지고 관리하기 어려워지면 분리하는게 맞지 않을까 싶습니다.
높은 응집도란 응집도 하나의 변경을 수용하기 위해 모듈 전체가 바뀐다 라는 측면에서 보면 결국 과도하지않은, 적절한 책임을 할당하는게 전제돼있는게 아닐까라는 생각도 드네요.
