### ISSUE TITLE
[5주차] 리팩토링의 다양한 기법

### ISSUE THREAD

**Issue by platanus-kr** [IDIOT-s/object-book-study#33]
이번주는 정말 코드도 내용도 많네요. 지난주는 이해하느라 고생했다면 이번주는 양에 압도되는 느낌입니다.

5장에서는 **책임 주도 설계** 방법으로 기존 코드를 어떻게 개선 하는지 소개하고 있네요. 책임 할당 위한 GRASP 패턴을 소개하고 있습니다. 하늘 아래 같은 설계는 없다는 모토가 꽂힙니다. 적절한 설계는 곧 합의된 설계라는 뜻으로 보이네요.

GRASP 원칙은 정리하자면 아래와 같습니다.

- 책임을 수행하는데 필요한 정보를 가지고 있는 객체에게 할당 하기
- 전체적인 결합도를 낮게 유지해 의존성을 낮추고 변화의 영향을 줄이기
- 높은 응집도를 유지할 수 있게 책임을 할당해 복잡성을 관리하기
- 객체 생성을 더 적절한 객체에게 할당하기 (위임)
- 역할을 활용해 객체의 타입을 추상화하여 다형적으로 행동하는 책임을 할당하기
- 구현이 변경되더라도 다른 객체에 영향을 미치지 않도록 캡슐화 하기

금주도 수고 많으셨습니다.

**Comment by unknownKade** [comment]
저도 5장이 2~4장과는 결이 다르다고 느꼈습니다. 지금까지 객체지향의 핵심을 하나씩 이해시켰다면, 책임 설계를 소개하며 그 모든 해심을 취합해서 어떻게 디자인 패턴으로 되는지를 소개하는 것 같아 이전처럼 이해하는 데에 어려움보다 양이 많고 앞의 단원과 비교하며 보다보니 한번에 소화하기 어려웠습니다.

코드가 많고 내용이 많은데 GRASP 원칙을 간결하게 잘 정리 해주셔서 감사합니다.
민철님도 금주 수고 많으셨습니다.
