### ISSUE TITLE
[5주차] 구조적 변화를 리팩토링 때 할 수 있나요

### ISSUE THREAD

**Issue by unknownKade** [IDIOT-s/object-book-study#34]
개인적으로 멘토님이 저번 주에 책을 스포(?) 해주면서 갈피 잡는데 많은 도움이 되었습니다. 항상 보면서 근데 이게 실무에서 어떻게 쓰이는지 경험을 토대로 생각하려고 했는데 책이 의도하는 바를 아니까 이게 원리적인 얘기고 그걸 이해해서 말하고 싶은 결론을 향하고 있단걸 염두하여 보게 되었습니다. 이번 장도 진호님 아니셨으면 GRASP가 너무 원리적인 얘기가 아닌가 이 원칙으로 어떻게 실제 프로그램을 설계 하는지부터 뜯다가 다 못 봤을 것 같습니다.

이번 장에서 특히 다형성 패턴에 관한 내용이 많은 도움이 되었습니다. 이런게 되는 특징이고 스프링에 경우 컨테이너 올라갈때 주입 시점과 상관있다 이런 것만 들었는데 조건 로직의 자리를 대신하는 명시적 클래스라고 생각하지 못했습니다. 생각해보면 단어 자체는 말 그대로 분명 이 타입인데 객체마다 조금씩 다르게 행동한다인데 거기까지 생각이 미치지 못했었습니다.

책임 주도적으로 설계하는 것은 리팩토링을 통해하는 것이 좋다고 제시하는데(p 166) 이에 대해서 어떻게 실무 경험 바탕으로 어떻게 생각하는지 각자 의견이 분분할 것 같아 듣고 싶스니다. 개인적으로 저는 실무에서 다른 사람들과 같이 협력하는데 구조를 바꾸는 것은 쉽지 않다고 생각합니다. 머지 전이라면 상관없겠지만 그 후부터는 이 변경으로 다른 곳이 터질 위험도 있고 개인적 경험으론 팀원들도 설계부터 변경은 대대적으로 하는것이 아니면 반대했을 것 같습니다. 유지보수와 확장성이 좋아지겠지만 그 고생의 값어치를 하는 리팩토링의 기준은 무엇이고 팀이 그걸 굳이..라고한다면 뭐라고 해야할까요?

**Comment by zinzoddari** [comment]
사실, 실무에서는 새 도화지에서 개발을 시작하게 되면 나름 팀 수준에 맞는 객체지향적 설계를 기반으로 코드를 작성하는 것 같지만, 우리 팀원 외의 이전 혹은 외주들이 작성한 코드는, 이해를 하지 못하는 순간이 바로 "레거시코드"가 되는 것 같아요. 
결국 이것을 우리 수준에 맞는 책임 주도 설계로 탈바꿈하기 위해서는 "리팩토링"이 결국 필요하닥고 봅니다. 

구조를 바꾸는게 쉽지는 않지만, 미래의 편의성을 위해서라면 먼저 나서서 주도하는 사람은 꼭 필요하지 않을까 싶어요.
사이드 이팩트를 최소한으로 만들기 위해서 테스트 코드도 열심히 작성하면서 검증의 단계를 거치는게 아닐까 싶습니다.

저는 코드 수준이 높아질 수록, 팀원들이 소속감을 가지게 되면서 이 소속감이 결국 남이 오고 싶은 집단이 되지 않는걸까? 생각하면서 열심히 리팩토링을 하고 있는데요...

이말 저말 하다보니 ㅎㅎ... 케이드님이 원하시는 대답인지는 모르겠으나 아무튼 리팩토링은 뭐든 다 중요하다!가 저에 결론이 될 것 같습니다 ㅋㅌ...

**Comment by beng9re** [comment]
> 개인적으로 저는 실무에서 다른 사람들과 같이 협력하는데 구조를 바꾸는 것은 쉽지 않다고 생각합니다. 머지 전이라면 상관없겠지만 그 후부터는 이 변경으로 다른 곳이 터질 위험도 있고 개인적 경험으론 팀원들도 설계부터 변경은 대대적으로 하는것이 아니면 반대했을 것 같습니다.

`이 변경으로 다른 곳이 터질 위험도 있고` ->  이 부분이 참 안타까우면서 슬픈 현실인거 같네요. 
진짜 중요한 비지니스에서는 리팩토링에서는 아무래도 겁부터 나기는 하더라구요.  
이 부분에 있어서 강력한 QA조직 혹은 테스트코드와 같은 안전 장치가 없다면 더욱더 심리적 압박감은 큰거 같아요. 

하지만 꾸준히 리팩토링을 하지 않으면 나중엔 N세대 프로젝트가 나오는게 현실인거 같아요. 
구축과 별개로 운영을 진행하면서 기능을 추가하면서 진행하다보면 변경에 취약해지고 변경이 감당이 안되니까 결국 시스템 통째로 재설계하는 N세대가 나오게 되는거 같습니다.  

결국 주저리 주저리지만, 
저의 개인적인 리펙토링 기준은 변경 사항이 생길때 그 부분에 리팩토링을 하면서 변경을 진행하는거 같아요. 
아무래도 큰 변경은 위험부담이 크고 함께 하는 팀원분들도 리스크가 있을꺼 같다는 생각이 들거든요. 
그 리팩토링을 티를 내면서 공유하다 보면 어느센가 같은편이 생기지 않을까해요 (정치를 하라는 의미 입니다.)

이렇게 점진적으로 바꿔보다 보면 "깨진 유리창이"  들깨진 유리창으로 탈바꿈하고 이쁜 유리창으로 되지 않을까? 합니다.
