### ISSUE TITLE
[5주차] 정리

### ISSUE THREAD

**Issue by JHwan96** [IDIOT-s/object-book-study#35]
이번 장에서는 데이터 중심 설계로 짰던 코드를 책임 주도 설계 방법으로 변경하는 것을 보여줍니다.

- 응집도를 이해하게 해주는 예시가 나온 것이 좋았습니다
    - 클래스가 하나 이상의 이유로 변경해야하는 것이라면 응집도가 낮은 것
    - 인스턴스를 초기화 하는 시점에 따라 서로 다른 속성들을 초기화한다면 응집도가 낮은 것
    - 메서드 그룹이 속성 그룹을 사용하는지에 따라 응집도의 높고 낮음을 의미
    
- 캡슐화는 이번장에서도 변경이 될 가능성이 있는가?에 따른다고 나왔습니다 :) 
   - 안정적인 인터페이스 뒤로 캡슐화하는 것이 좋음

질문
- 메소드의 응집도를 높이기 위해 잘게 쪼개는 것이 언제나 좋을까요?

**Comment by platanus-kr** [comment]
클래스 내 메소드는 언제나 한가지의 역할만 하는것이 단위 테스트에도 용이하고, 변경 했을때 영향도 예측이 충분히 쉽고, 무엇보다 코드 흐름이 쉽게 읽히는것 같아요. 

4번째 소단원에 보면 몬스터 메서드인  `ReserverAgency.reserve()` 를 리팩토링 하는 내용이 나오죠.. p169 의 메서드를 p172 에서 정리를 하는데요. 두개를 양쪽에 같이 놓고 한번 비교해보시면 '메소드는 왜 하나의 역할만 하는것이 좋은가' 에 대한 답변이 될 것 같습니다.
금주도 고생 많으셨고 내일 만나요!

**Comment by idid93** [comment]
5장에서 메소드를 작게 나누는 것은 응집도를 높이기 위해서였지만 그 외에도 책 초반(p31)에 코드의 중복을 제거하고 표현력을 높이기 위해서라고 나온 부분도 있습니다. 계속해서 다른 이유도 나올 것이라고 생각하지만 언제나 답이라고 생각하지 않습니다. 사용이 특수하고 논리적으로 불변으로 간주 되는 행동은 한 큰 메소드에 담는 것이 파이프라인 파악이 쉬운 경우도 존재할 것 같습니다.
금주도 수고 많으셨습니다!

**Comment by unknownKade** [comment]
5장에서 메소드를 작게 나누는 것은 응집도를 높이기 위해서였지만 그 외에도 책 초반(p31)에 코드의 중복을 제거하고 표현력을 높이기 위해서라고 나온 부분도 있습니다. 계속해서 다른 이유도 나올 것이라고 생각하지만 언제나 답이라고 생각하지 않습니다. 사용이 특수하고 논리적으로 불변으로 간주 되는 행동은 한 큰 메소드에 담는 것이 파이프라인 파악이 쉬운 경우도 존재할 것 같습니다.
금주도 수고 많으셨습니다!

**Comment by unknownKade** [comment]
철환님 : 필요에 의해 메소드를 나누는 것이 맞다. 명확하다면 나누는 것이 좋지만, 예외 케이스가 계속 생기는 경우 등을 고려해야 한다.   
병희님 : 책임을 기준으로 먼저 테스트 코드를 짠다.
