### ISSUE TITLE
[5주차] 내용 정리

### ISSUE THREAD

**Issue by yeongsik** [IDIOT-s/object-book-study#37]
# 5장 책임할당하기

### 책임주도 설계를 위한 장
* 3장부터 시작되는 설계에 대한 내용에 좀 더 디테일한 방법들과 실제 개발하면서 사용할 법한 팁들을 알려주고 있는 챕터였던 것 같습니다.

### GRASP 패턴

1. INFORMATION EXPERT(정보 전문가)
   * 필요한 정보를 갖고 있는 객체에게 책임 할당
2. LOW COUPLING
   * 설계의 전반적인 결합도가 낮게 유지되도록 책임 할당
3. HIGH COHESION
   * 높은 응집도를 유지할 수 있게 책임을 할당
4. CREATOR 패턴
   * 객체 생성 책임에 대한 패턴, 객체 A를 생성해야 할 때 어떤 객체에 해당 책임을 할당해야하는가?
     1. B가 A 객체를 포함하거나, 참조
     2. B가 A 객체를 기록
     3. B가 A 객체를 긴밀하게 사용
     4. B가 A 객체를 초기화하는데 필요한 데이터를 갖고 있음
   * 위의 조건이 만족하는 객체한테 생성 책임을 핟랑해야한다.

5. POLYMORPHISM 패턴
   * 객체의 타입에 따라 변하는 로직이 있을 때 if ~ else 혹은 switch case 등의 조건 논리로 처리하기보단 다형성을 이용해 새로운 변화를 다루기 쉽게 하자

6. PROTECTED VARIATIONS 패턴
   * 다형성으로 책임을 분산 시킨 후 안정적인 인터페이스 뒤로 변경을 캡슐화
   * 코드 수정의 파급효과를 줄인다.
   * DiscountCondition 타입들을 다형성으로 책임을 분산시킨 후 Movie에 있는 각 타입의 Condition들을 DiscountCondition 인터페이스로 변경하는 방법

### 현실에서 책임주도설계
* 우선 기능 구현부터 진행하자. 처음에는 책임할당은 어려울 수 있기 때문에 
* 몬스터 메서드를 만든 후 위에 배운 GRASP 패턴을 적용해보자

### 인상 깊었던 점
* 우선 기능구현부터 진행하고, 그 후에 리팩터링으로 책임할당을 하자라는 부분이 인상 깊었습니다.
* 책임주도설계에 대한 GRASP 패턴이 소개가 되어서 책임주도 설계 함에 있어서 툴 혹은 구체적인 방법론이 생긴 것 같아서 모호했던 개념들에 대해서 이해가 잘 되었던 장이었습니다.

**Comment by unknownKade** [comment]
GRASP의 원칙을 꼼꼼하게 정리해주셔서 내용이 정리되네요. 저도 이번 장에서 어떻게 책임 지향적으로 바꿔 나가야 하는지 구체적으로 다뤄서 좀 더 감이 잡히는 것 같습니다.
