### ISSUE TITLE
[5주차] 정리 및 후기

### ISSUE THREAD

**Issue by ch200203** [IDIOT-s/object-book-study#38]
책임주도 설계를 위하여 우리가 고려해야할 원칙 두가지가 있었는데요.

`데이터보다 행동을 먼저 결정하라`

`협력이라는 문맥 안에서 책임을 결정하라`

이해하는게 참 어려웠지만 쉽게 이야기하면

> 메시지를 결정하고 이 메시지를 누구에게 전송할지 찾아본다.
클래스 기반설계 → 메시지 기반의 설계로!
객체를 가지고 있기 때문에 메시지를 보내는 것이 아니라, 메시지를 전송하기 때문에 객체를 갖게된 것
> 
- 결론은?
→ 전송할 메세지를 결정한 후에야 비로소 객체의 상태를 저장하는 데 필요한 내부 데이터에 관해 고민해봐야 한다.

그래서 고민을 어디서부터 해야하나 막막했는데 GRASP 패턴을 제시하여 어느정도 가이드라인을 주는 것 같습니다.

### 도메인을 기반으로 생각해보기

- 설계를 시작하는 단계에서는 개념들의 의미와 관계가 정확하거나 완벽할 필요가 없음
→ 너무 많은 시간을 들이지 말고 빠르게 설계와 구현을 진행해보자

### 정보 전문가에게 책임을 할당하라

- 제공할 기능을 어플리케이션의 책임으로 선택한다.
- 이 책임을 전송된 메세지로 간주하고 이 메세지를 책임질 첫번째 객체를 선택한다.

> ***메시지를 전송할 객체는 무엇을 원하는가?***

> ***메시지를 수산할 적합한 객체는 누구인가?***

- 객체의 책임과 책임을 수행하는 데 필요한 상태는 동일한 객체안에 존재해야함
- 따라서, 첫째 원칙은 책임을 수행할 정보를 알고있는 객체에게 책임을 할당해야 한다.
→ Information Expert(정보전문가)패턴 이라고 함!

### 책임 주도 설계의 대안
아무것도 없는 상태에서 책임과 협력에 관해 고민하기 보다는 일단 실행되는 코드를 얻고 난 후에 
코드 상에 명확하게 드러나는 책임 들을 올바른 위치로 이동시키는 것 → 결국 중요한 것은 `리팩토링`

### 설계를 주도하는 것은 ***변경***
1. 코드를 이해하고 수정하기 쉽도록 최대한 단순하게 설계 
2. 코드를 수정하지 않고도 변경을 수용할 수 있도록 코드를 더 유연하게 만드는 것
대부분의 경우 '1'이 더 좋은 방법이지만 유사한 변경이 반복적으로 발생하고 있다면 복잡성이 상승 하더라도 유연성을 추가하는 '2'의 방법이 더 좋다.

### 메서드 응집도
긴 메서드는 다양한 측면에서 코드의 유지보수에 부정적인 영향을 미친다. 

- 어떤 일을 수행하는지 한눈에 파악하기 어렵기 때문에 코드를 전체적으로 이해하는 데 너무 많은 시간이 걸린다.
- 하나의 메서드 안에서 너무 많은 작업을 처리하기 때문에 변경이 필요할 때 수정해야 할 부분을 찾기 어렵다.
- 메서드 내부의 일부 로직만 수정하더라도 메서드의 나머지 부분에서 버그가 발생할 확률이 높다.
- 로직의 일부만 재사용하는 것이 불가능하다.
- 코드의 재사용하는 유일한 방법은 원하는 코드를 복사해서 붙여넣는 것뿐이므로 코드 중복을 초래하기 쉽다.

클래스가 작고, 목적이 명확한 메서드들로 구성돼 있다면 변경을 처리하기 위해 어떤 메서드를 수정해야 하는지를 쉽게 판단할 수 있음
객체로 책임을 분배할 때 가장 먼저 할 일은 메서드를 `응집도` 있는 수준으로 분해하는 것

### 객체를 자율적으로 생성하기

**어떤 메서드를 어떤 클래스로 이동시켜야 할까?**
자신이 소유하고 있는 데이터를 자기 스스로 처리하도록 만드는 것! 
따라서 메서드가 사용하는 데이터를 저장하고 있는 클래스로 메서드를 이동시키면 된다.

**Comment by zinzoddari** [comment]
책 한번 훑고 철환님 정리 글 보니, 더 이해가 잘 되면서 그래도 책 잘 읽었구나~ 생각이 들었습니다 ㅎㅎ
이번에 패턴에 대해서 많이 알려줬는데, 사실 그냥 이렇게 있구나~ 만 느껴졌지만, 이번에 다들 많이 정리들 하셔서 놀랐어요.
철환님은 이러한 패턴들.. 뭐가 뭔지 다 이해가 되시나요 👀?
