### ISSUE TITLE
[ 1주차 - 개요 ] 클래스 다이어그램, 커뮤니케이션 다이어그램, 패키지 다이어 그램의 사용처와 의미

### ISSUE THREAD

**Issue by beng9re** [IDIOT-s/object-book-study#4]
책에서는 클래스 다이어그램, 커뮤니케이션 다이어그램, 패키지 다이어 그램을 개요부분에서 보여주고 있는데요
책에 설명한거 이외의 어떠한 효과를 얻을 수 있는지 한번 논의 하고 싶습니다!

* 클래스 다이어그램 
![image](https://github.com/IDIOT-s/object-book-study/assets/26699273/0aa2ecdb-6cef-4819-b7ed-ad1ac91a3e1c)

* 커뮤니케이션 다이어그램 
![image](https://github.com/IDIOT-s/object-book-study/assets/26699273/592ec9f9-3f19-4e7a-bdc6-ca5c2c9a6616)

* 패키지 다이어그램
![image](https://github.com/IDIOT-s/object-book-study/assets/26699273/422e0064-a398-4cac-aebe-0182c646fa99)

각 다이어그램 사진 출처 : 오브젝트 책 - 조영호 님

**Comment by platanus-kr** [comment]
코드는 지난번 진호님 강의 진행으로 같이 많이 봤기에 저도 이번엔 다이어그램 위주로 봤었는데요.
패키지를 분리함에 있어서 접근자에 따른 캡슐화를 해볼수도 있겠다는 생각이 드네요!

[![image](https://github.com/IDIOT-s/object-book-study/assets/6806008/d2d4058f-6485-4c29-a5e3-536fa5314628)](https://iq.opengenus.org/public-private-protected-in-java/)
