### ISSUE TITLE
[ 5주차 ] 후기 

### ISSUE THREAD

**Issue by beng9re** [IDIOT-s/object-book-study#40]
책 제목 그대로 코드로 이해하는 객체지향이라는 말이 어울리는 파트였네요.

사실 진득하게 코드를 직접 변경하면서 책을 읽어야 어느정도 이해가 되는 파트라고 생각이 들었습니다.

GRASP 패턴을 통해 객체에게 책임을 할당할 때의 원칙을 설명하지
코드와 그림을 번갈아 보아야 해야 이해가 되었던거 같아요.

그 중 DI 감춰져서 어딘가는 객체를 생성해야 하는데 라고 생각하는데
`CREATOR` 패턴을 통해 생성을 바라볼 수 있게 되었네요.

이번장에서 결론에서 나오듯 `코드를 작성한 후에 리펙터링 하는것이 더 훌륭한 결과물이 낳을 수도 있다`고
하는데 이 부분이 많이 공감이 되었습니다. 

> 
하하.. 이번장은 여러일들이 있어 코드를 직접 변화시키지는 못했는데 찬찬히 해봐야겠습니다.

**Comment by unknownKade** [comment]
GRASP 에 대해 보며 객체지향의 모범으로 꼽히는  스프링이나 디자인패턴이 왜 그렇게 만들었는지 알아가는 장이 되었습니다.
