### ISSUE TITLE
[6주차] 디미터의 법칙과 명령-쿼리 분리 원칙

### ISSUE THREAD

**Issue by platanus-kr** [IDIOT-s/object-book-study#41]
5장까지 객체에 대한 이야기가 주로 오갔다면 6장은 메서드에 대한 리팩토링 이야기가 나오네요.

크게 디미터 법칙과 명령-쿼리 분리원칙으로 나눌 수 있을것 같아요.
객체에서 원하는 데이터를 꺼내거나 내부 퍼블릭 인터페이스를 호출하기 위해 줄줄이 메서드 호출을 하는게 일반적인데요. 이것이 내부 구현에 대한 노출로 기차충돌이 일어나고 나아가 캡슐화를 깨뜨린다는 점을 들어 디미터 법칙을 뒷받침 하는 설명으로 참 좋았다고 생각합니다.

그리고 명령-쿼리 분리 원칙에서 저도 참 햇갈렸던 내용이 나오는데 프로시저와 함수의 구분입니다. 프로시저는 부수효과를 발생시킬 수 있고, 함수는 부수효과가 없다는 점을 잘 정리해놓은것 같습니다. 그래서 모호하게 알고 있었던 함수형 프로그래밍의 장점으로 참조 투명성을 지킬 수 있고 프로시저로 작성하는 전통적인 코딩에 비해 실행 결과의 예측이 쉬우며 따라서 병렬 처리에서도 프로시저에 비해 동시성 문제가 발생하지 않으니 보다 용이하다는 점. 왜 함수형 프로그래밍이 좋은가에 대해 알 수 있었습니다. (누가 물어보면 바로 써먹기 ㅋㅋ)

금주도 고생 많으셨습니다.

**Comment by zinzoddari** [comment]
저도 함수형이 매번 좋다좋다만 알았지 그래서 함수형이 왜 좋은디... 이해를 못했는데
이번 기회를 통해서, 나름 혼자 함수형이 받은 인자만을 가지고 처리를 하기 떄문에, 민철님이 말씀하신 동시성 문제에 대해 조금 덜 영향을 받지 않는가. 라고 혼자 결론을 내렸습니다. 

예전엔 정말 .getA().getB().getC().. 이런 _kuso_ 코드 작성을 해놓고도 이게 맞나.. 그렇다고 다른 방법이 있는 것도 아니잖아? 했었는데, 요즘 들어 이런게 "냄새 나는 코드"라는 걸 좀 인지하게 된 것 같아요..ㅎ... 이번 장 확실히 이전 장보다 잘 읽히고 재밌던 것 같네욥.

고생하셨습니다 ~

**Comment by midcondria** [comment]
저도 프로시저, 함수를 구분해서 설명해주는 부분이 좋았습니다.
이 책을 읽고 나면 어떤 개념에 대해 설명할때 단순히 짱무위키에 적혀있는 설명 읊기보다는 더 자신만의 언어로 답변할 수 있을거 같아요~
