### ISSUE TITLE
[6주차] 간단 후기 및 간단 질문

### ISSUE THREAD

**Issue by zinzoddari** [IDIOT-s/object-book-study#42]
갈수록 장마다의 범위가 꽤 늘어나서 책 읽기가 벅차네요 😂
다행히 6장의 경우 이전 장과는 다르게 내용이 슉슉 읽혔습니다.

이번 장을 읽으면서 느꼈던 점으로는, 내가 생각보다 알아서 잘 코드를 짜고 있었구나! 였습니다.

### 디미터 법칙 
- 객체의 내부 구조에 강하게 결합되지 않도록 협력 경로를 제한하라는 것
- 낯선자에게 말하지 말라, 혹은 오직 인접한 이웃하고만 말하라
- 오직 하나의 도트만 사용하라
- 부끄럼타는 코드를 작성할 수 있다.

```메세지 수신자.getA().getB().getC()...``` 이러한 형식을 ```기차 충돌```이라고 하는데, 이러한 코드는 ```결합도```를 높인다는 생각으로 지양을 해 왔던 것이 결국 디미터 법칙을 나도 모르게 잘 지킨다고 생각이 들었습니다. 😂

또, 정확한 의도를 드러내기 위한 인터페이스의 이름을 짓기 위해서는, 확실히 아는 영어 단어가 많아겠다~ 싶었는데
정말 영어 공부는 왜이리 하기 싫은걸까요 ㅎ..

### 명령-쿼리 분리 원칙
- 객체의 상태를 변경하는 명령은 반환값을 가질 수 없다.
```java 
public void boardRemove(Board board) {
     board.remove();
}

public class Board {
    private boolean useYn;

    public void remove() {
        this.useYn = USE_YN.N;
    }
}
```
평소에도 위와 같은 습관대로 상태를 변경할 때에는 반환 값 없이 처리를 했던 습관이 있고,
- 객체의 정보를 반환하는 쿼리는 상태를 변경할 수 없다.
```java 
public void validBoard(Board board) {
     if(board.isUse()) { }
     ...
}

public class Board {
    private boolean useYn;

    public boolean isUser() {
        return isUse;
    }
}
```
같은 형식으로 상태에 대해서 가져올 때에는 상태만을 가져오도록 구현을 하는 것 같은데

만약, 이 둘을 같이 하고 싶다 하면, 이는 서비스 계층.. 즉 메세지를 발송하는 쪽에서 부르고, 바꾸고의 작업을 처리를 해주는게 맞는걸까요?

하나 더, 디미터 법칙은 하나의 도트를 강제하는 규칙은 아니라고는 하는데
저는 하나의 도트로 써야 가독성이 높아진다고 생각이 드는데요.
다들 어떠한 개발 스타일이신지, 어떤 생각이 드시는지 궁금하네요 😊

**Comment by platanus-kr** [comment]
1. 이 둘을 같이 하고 싶다 하면...
-> 만약 행동을 합쳐야 하고 메서드 수준이 아니라면, 파사드 패턴으로 해결할 수 있지 않을까요? 

2. 저도 앞으로는 코딩할때 좀 챙겨서 보려구 합니다. ㅎㅎ

**Comment by midcondria** [comment]
역시 세상에서 제일 어려운게 이름짓기 같아요...
제가 질문 의도를 제대로 이해한게 맞다면
1. 비즈니스 로직에서는 조회와 상태변경을 동시에 하는 로직이 있을 수 밖에 없는것 같아요. 
책에서도 반환 값을 가지고 쿼리인척 하면서 상태를 바꾸던 isSatisfied() 를 리팩토링해서 isSatisfied() 와 reschedule() 을 분리한 뒤에
isSatisfied() 호출 후에 if(!isSatisfied){  reschedule()  } 이런 식으로 호출 하는걸 보면 메서드 명을 보고 개념을 정하고 그걸 쪼개는 식으로 관리하라는 뜻인것 같습니다.
2. 저도 웬만해서는 최대한 도트를 줄이는게 좋은것 같아요. 그런데 stream 이나 MockMvc 이용할때 메서드 체이닝 이용하는 방식은 괜찮은거 보면 이것도 하기 나름지 않을까? 싶습니다.

**Comment by ch200203** [comment]
해당 장을 읽으면서 최근에 짯던 코드를 돌아가서 보니 생각보다 위와같은 내용을 잘 지켜서 짯더라구요. (역시 돈의힘)

다만, 디미터 법칙을 완벽하게 지키기 위해서 코드의 양이 계속해서 늘어나는 부분은 무시하지 못할 부분일 것 같습니다..!

**Comment by beng9re** [comment]
1. 역할을 잘 생각해서 해당 협력이 이루어지는 객체의 메서드 수준에서 합칠꺼 같아요. 진주님이 생각하는 부분이 서비스 계층이라면 서비스 계층의 메서드에서 말씀하신대로 수행할꺼 같아요.

2. 도트를 하나만 유지하는것 Stream API나 불변성을 유지하는 함수형 프로그래밍에서는 하나씩 유지하면 각단계가 명확해지지만 
스트림의 각 단계 별로 변수명을 생각하고 진짜 이름을 생각하다 보다보면 적절한 이름을 선택하지 못해서 결국 어? 이부분이 뭐하는거지? 생각이 들더라구요. 이런 경우에는 적절한 도트에서 의미있는 메서드를 만들고 합치는게 가독성을 유지하게 되는거 같아요.
