### ISSUE TITLE
[6주차] 정리 - 부여한 책임에 대한 구체적인 구현 방법

### ISSUE THREAD

**Issue by yeongsik** [IDIOT-s/object-book-study#43]
5장에서는 설계할 때 어떤 객체에 책임을 부여할까에 대한 방법론이 GRASP 패턴을 통해 설명했었습니다. 6장은 거기에 이어서 부여 받은 책임에 대한 구현에 대한 구체적인 법칙들을 설명해주는 장이었다고 생각이 드네요.

책임에 대한 단어 정리(메세지, 퍼블릭 인터페이스, 오퍼레이션, 메서드 등)를 통해서 읽으면서 모호했던 개념들이 명확해졌고,
디미터의 법칙, 묻지말고 시켜라, 인터페이스의 의도 드러내기 같은 법칙을 통해 책임을 어떻게 구현 또는 리팩토링해야 할지에 대한 것을 배웠던 장이었습니다.

인상깊었던 점은 상황에 따라 원칙을 깨야하는 경우를 말해주는 부분이었습니다. 토론하면서 매주 마다 나왔던 내용이었지만 책에서도 다시 한번 일깨워줌과 동시에 예외 적인 상황들에 대한 설명이 저는 좋았습니다.

**Comment by midcondria** [comment]
저도 이 책의 기본 기조가 "은총알은 없다", "원칙을 맹목적으로 따르지 말고 제대로 이해하고 스스로 판단해서 쓰는 능력을 길러라" 라서 굉장히 좋았습니다.
