### ISSUE TITLE
[6주차] 명령 쿼리 분리 경험이 궁금합니다.

### ISSUE THREAD

**Issue by yeongsik** [IDIOT-s/object-book-study#44]
책에서 나온 명령 쿼리 분리 원칙을 읽으면서 실제 사용 경험에 대해 궁금했습니다.
책에서는 메서드에 국한되어서 설명을 해주는데 실제로는 이런 명령 쿼리 분리 원칙이 어떻게 되나요?

**Comment by platanus-kr** [comment]
실제로도 책에 있는 예제랑 비슷하지 않을까요? 예를들어 `is~` 나 `get~` 같은 조회 성격의 작은 역할을 해야 하는 메서드에서 상태를 변경하거나 저장하는 측면은 좋지 않겠지요. 그래서 책에서도 조회 메서드에 합칠게 아니라 호출하는 쪽에서 조회에 대한 판단을 해야 한다고 코드로 설명하는 것 같아요.

```java
if (!event.isSatisfied(schedule)) {
    event.reschedule(schedule);
}
```

**Comment by midcondria** [comment]
이게 MSA 만 그런지는 저도 잘 모르겠지만 몇몇 강의에서는 MemberRepository 를 작성할 때 아예 
MemberReadRepository, MemberWriteRepository 이렇게 구분해서 쓰기도 하더라구요.
이런 쪽은 오늘 있을 토론 시간에 다른 분들과 이야기를 나눠보면 재밌을것 같습니다

**Comment by ch200203** [comment]
명령 쿼리 분리 원칙은 보통 `CQS` 라고해서 함수레벨에서 적용되는 개념입니다. 

이를 더 확장하여 서비스 설계(=아키텍쳐)에 적용하게 되면 데이터베이스를 나누게 되는데 이를 `CQRS 패턴`이라고 합니다.  때문에 CQRS를 적용한다면 당연하게도 CQS 역시 적용되고 있죠.

명령(Command)와 쿼리(Query) 는 각각 데이터의 변경과 조회를 담당합니다.
이를 분리하여 함수레벨에서 책임을 분리하고 가독성을 높이기 위한 방법이라고 생각하면 좋을 것 같아요.

추가적으로, `CQRS` 를 구성하는 마이크로 서비스 아키텍쳐(MSA)는 CQS 사상을 포함하고 있는 것이지, CQS만을 위해서 구성된 방식은 아니기 때문에 이에 대해서는 @midcondria 님과 같이 오늘 이야기를 나눠 보면 좋을 것 같습니다. :)

CQRS에 대해서는 아래의 발표와 글에서 간단하게 설명하고 있어 참조하시면 더욱 좋을 것 같습니다 :) 
https://youtu.be/38cmd_fYwQk 
https://stackoverflow.com/questions/34255490/difference-between-cqrs-and-cqs

**Comment by platanus-kr** [comment]
모임에서 이야기하면서 전하려고 했는데 깔끔하게 정리된 짧은 댓글이 있어서 같이 공유드립니다
https://stackoverflow.com/a/34280756

**Comment by beng9re** [comment]
질문하신 내용만 사례를 들자면 
메서드 수준에서만 단순하게 썻던거 같아요 
상태를 변경한다 -> Void 타입으로 하고 내부 상태만 변경하는 로직 작성 
쿼리를 해온다. -> 반환타입이 만약에 다르다면,  Stream 같은 도구를 이용해서 불변성을 유지해서 데이터를 반환해줍니다. 참조성이 있는 객체인경우에는 심각하게는 새로운 객체를 만들기도 합니다.
