### ISSUE TITLE
[6주차] 디미터 법칙을 구현하면서 느낀점

### ISSUE THREAD

**Issue by ch200203** [IDIOT-s/object-book-study#46]
디미터 법칙을 보면서 객체지향생활체조 원칙에과 관련된 생각들이 많이 떠올랐습니다.

일급컬렉션, 원시값 포장 등을 하고 디미터 법칙 등 객체지향 원칙을 지키려고 노력하다 보면 
발생할 수 있는 몇가지 궁금한 점에 대해 여러분은 어떻게 생각하시는지 궁금합니다.

예를 들어 아래와 같은 코드가 존재한다고 할 때

```java
class User {
  private Age age;
  ...
  
  public boolean isAdult() {
    return age.isAdult();
  }
}

class Age {
  private static final int DEFAULT_ADULT_AGE = 19;
  
  private int age;
  
  public boolean isAdult() {
    return DEFAULT_ADULT_AGE < age;
  }
}
```

우리는 `User`가 성인인지 알기위해서 메시지를 보냅니다.
이 과정에서 `user().isAdult();` 라는 메시지와 `age.isAdult();` 라는 두개의 메시지를 사용해서 보내게 됩니다.

이 때 `User` 객체와 `Age` 객체에 같은 네이밍의 메서드가 사용되게 되는데 이렇게 ***같은 이름의 메서드를 명명*** 하는 경우에 혼란이 없을까? 라는 의문이 듭니다.

User 클래스에서 isAdult는 사용자가 성인인지 여부를 판단하는 것을 책임지고, Age 클래스에서는 나이가 성인 나이인지를 판단 한다고 생각합니다. 이러한 경우에 저는 책임이 잘 분리 되어있다고 생각하고 있습니다.
**컨텍스트에 따른 의미**에 의해서 같은 이름의 메서드라도 클래스에 따라 다른 의미를 표현하고 있다고 생각합니다. 이 경우에는 User의 성인 여부와 Age의 수치가 성인 기준을 만족하는지에 대한 차이가 있다고 생각하는데. 여기서 컨텍스트에 따라서 적절한 메서드 명을 다시 지어 주어야 하냐는 생각이듭니다.

두번째로는 지금은 `User -> Age`로의 단순한 구조이지만
`A -> B -> C -> D -> E` 의 복잡한 순서로 객체에게 계속 메시지를 보내는 경우 코드의 양이 증가하게 되고 각 단위 테스트도 의미 없는 테스트가 증가될 가능성이 있다고 생각합니다.
과도한 메서드 체인 구조는 오히려 유지보수를 복잡하게 하지 않나 라는 생각을 해봅니다.

위 내용들에 대해서 여러분들의 생각은 어떠신가요?

**Comment by ch200203** [comment]
자문자답이긴한데 두번째 내용의 경우에는
인터페이스를 통해서 추상화 하거나, 디자인 패턴(파사드, 커맨드 패턴 등...)을 사용하면 될 것 같다는 생각이드네요.

**Comment by midcondria** [comment]
1. 첫 번째 질문은 controller, service 짤때 맨날 이름 똑같이 지으면서 같은 생각을 한거 같아요 ㅋㅋ 
이건 결국 팀바팀의 문제 같지만 호출할 때 class.메서드() 이렇게 호출 할테니 이 문맥상으로 봤을 때 문제가 안생긴다면 같은 이름의 메서드를 써도 괜찮지 않을까? 하는 생각이 들었습니다.
2. 두번째 질문은 적절하지 못한 예시일 순 있지만 저도 아래 같은 구조를 어떻게 고쳐야하나 할때 같은 생각을 해봤는데 참 어려운거 같아요.
![image](https://github.com/IDIOT-s/object-book-study/assets/119824778/84e88b1d-091a-4f90-957e-29b8efd0c581)
그런데 책에서 나온것 처럼 디미터 법칙을 맹목적으로 따르다가는 오히려 응집도 낮은 클래스들이 잔뜩 생길 수도 있으니까 적절한 선에서 고치는게 맞는것 같습니다.

**Comment by beng9re** [comment]
1. 저는 같은 메서드명으로 써야되는 상황이라면 써도 된다 라는 입장입니다.
가독성 측면으로는 훨씬 유리해요.
```
User 철환님;
철환님.isAdult();
 
Age 철환님의 나이 = 철환님.age();
철환님의 나이.isAdult();
```
말로는 표현을 못하겠는데 코드로 보면 이런 효과를 날꺼 같네요 

2번은 흠.. 자문자답하셔서 넘어가겠읍니다..ㅎ;
