### ISSUE TITLE
[6주차] 후기와 토론거리?

### ISSUE THREAD

**Issue by beng9re** [IDIOT-s/object-book-study#48]
### 후기 
6장의 제목은 메시지와 인터페이스지만, 
결론적으로는 객체끼리와의 소통의 방식인 좋은 `퍼블릭 인터페이스`에 대해서 정리를 해주면서 소개 했던 장이었던거 같습니다.

명령 쿼리분리나 디미터의 법칙등과 같은 도구를 통해서 말이죠.

제가 가장 크게 깨닳았던 점은 
평소에 메서드에 의도를 담는것을 좋겠다. 라고 생각해서 메서드 이름을 의도를 구체적으로 적었던 습관들이 있었는데 
P188부분에 나오죠.  
-> 호출하는 클라이언트 입장에서 상세내용을 알아서 캡슐화를 깨고 변경에 취약하는 코드를 양산한다는 사실을요.

지난일을 보다보니 평소에 짰던 코드들을 보면 하나에 메서드를 변경하면 여려군데에 변경에 작업이 생겼던거 같아요.
그래서 "어떻게 하는것이 아니라 **무엇을** 하는지 메서드의 명명"을 하고 넘겨주는 파라미터 또한 주의해서 넘겨야겠다는 생각이 들었습니다.
> 저의 말로 표현하자면 메서드이름을 추상화 하고 파라미터를 일반화 하는것이라고 표현할 수 있겠어요.

### 공유하고 싶은 내용
그리고, CQS (명령 쿼리 분리)에 대해서는 너무나 책에 잘 설명이 되었고, 
개인적으로 책 이외에 개인적인 경험에 의한 장점은 Query 메서드에서는 반환값이 있고 Command는 반환값이 (void) 타입이다 보니. 
대략적으로 Command는 해당 메서드는 내부 상태를 변경하는구나, Query는 내부의 상태를 변경하지 않는구나를 생각해서 `부수효과`가 있음과 없음을  자연스럽게 반환 타입만 보고도 파악이 가능한 장점이 있었습니다. 

### 토의 거리 
이번장에서의 메인 주제를 살짝 벗어나는 토의거리이긴 한데 
여러분들이 사용하고 있는 레이어드 아키텍처를 주로 사용하실텐데 각 레이어별로의 역할과 책임은 무엇이 인지?
이 레이어에 주로 사용되는 클래스메 서들은 저희가 생각하는 퍼블릭 인터페이스의 관점으로 접근하는게 맞을까요?
각 메서드는 개인적으로 생각하기에는 일종에 Facade(창구) 혹은 진입점의 역할을 수행한다고 생각합니다

ps. 요즘 정신이 없어서 생각이 많아지는데요
지금 제가 하는 일들이 너무나 비동기적인(거이 5분대기조 상황입니다..) 내용이 많아서 시간이라는게 모호해서 차주중에는 어느정도 해결이 가능할꺼 같아요.
정해진 시간에 참여는 어렵더라도 코멘트라도 글로써 적극 참여 하겠습니다.

**Comment by midcondria** [comment]
저도 "메서드이름을 추상화 하고 파라미터를 일반화 하는" 습관을 들이는게 중요하다는 생각이 들었어요.
CQS 에서도 Query 는 값을 반환하고, Command 는 void 로 확실히 구분해두면 디버깅하기 편할것 같습니다.
토의 거리에 대한 제 생각은 Facade 도 일종의 인터페이스니까 퍼블릭 인터페이스의 관점으로 접근하는거랑 같지 않을까? 라는 생각이 듭니다!
