### ISSUE TITLE
[6주차] 정리 및 질문

### ISSUE THREAD

**Issue by JHwan96** [IDIOT-s/object-book-study#49]
- setter를 사용하면 안된다는 것을 다시한번 확인한 것 같습니다.
    - 의도를 파악하기 힘들다는 문제가 있다는 것
    - 코드의 목적을 의도가 있는 이름을 통해 명확하게 커뮤니케이션 해야함
- 생각보다 처음 접하게 되는 원칙이나 용어가 많았는데 코드를 통해서 잘 이해할 수 있어서 좋았습니다.
- 명령 쿼리 분리 원칙 (CQS)에 대해서 처음 알게 되었는데 값의 반환과 상태 수정을 같이 두는 것이 어떤 변수를 만들어내는지 쉽게 이해되서 좋았습니다.
    - 그렇지만 이 원칙이 실제로 쓰이는지는 감이 잘 안오네요 😢

**질문**

1. 이번 장에 나온 원칙들이 부적합해서 무시하고 코드를 짰던 경험이 있으신지 궁금합니다 :)
2. 이런저런 원칙을 지키다보면 코드가 계속 늘어나는 것은 어쩔 수 없는 부분인 것 같아 보입니다. 코드의 양이 늘어나는 것을 어느정도 참작하시는지 궁금합니다.

**Comment by midcondria** [comment]
1. 원칙이 부적합하다기 보다는 현실과 타협해서 어기고 코드를 작성하는게 크지 않을까 싶습니다.
2. 책에서도 얘기 하듯 유연한 코드를 짜려면 추상적으로 코드를 짜야하고, 그러려면 1개 클래스로도 될거도 여러개 클래스로 만들어야 하죠. 이건 뭐 이론적으론 코드가 몇배가 되든 좋은 설계를 따라가는게 맞지만 당장 주어진 환경에서 타협해서 해야하는 부분이라 정답은 없을것 같습니다.

**Comment by platanus-kr** [comment]
그렇지만 이 원칙이 실제로 쓰이는지는 감이 잘 안오네요 -> 어떤 역할을 하는 메소드에서 상태를 변경하는 부분만 메소드로 따로 분리한다고 보면 어떨까요?
