### ISSUE TITLE
[1주차] 데이터를 스스로 관리한다는 것

### ISSUE THREAD

**Issue by platanus-kr** [IDIOT-s/object-book-study#5]
첫주 리뷰 겸 토론 주제 입니다.
앞서 두분이 1장 정리를 멋지게 해주셔서 저는 토론 주제를 좀 올려볼까 합니다.

1장에서 하고자 하는 말은 결국 소프트웨어 모듈의 목적에 따라 `변경이 용이한 코드`가 왜 중요한지 설명하기 위해 객체지향 설계에서는 코드를 어떻게 분리해야 하며, 이를 했을때 유지보수 측면에서 어떤 장점이 있는지 설명했다고 이해가 됩니다.

그러면서 캡슐화를 통해 `객체의 자율성`을 통해 `스스로 데이터를 관리하는 객체`를 설명하는데요. (책임의 적절한 이동이나, 높은 응집도 같은 이득도 있지요)

책에서는 데이터를 스스로 관리하게 되면 데이터의 변경으로 부터 영향도를 최소화 된다는 잇점을 소개하는데요.,   
객체의 관점에서 데이터를 관리한다는 것이 어떤것인지 여러분들의 의견이 궁금합니다.

제 생각에는 결국 객체는 어쩔수 없이 의존을 가지게 되고 일부 의존에 따라 '스스로' 관리가 100% 되지는 않을것 같다는 생각인데요.
이 주제로 자유롭게 이야기 나눠봤으면 좋겠습니다.

금주도 수고 하셨고 금요일에 뵙겠습니다.

**Comment by beng9re** [comment]
그 주차의 주인들은 코멘트달분들이 없군요🥲 -> 논의 해봐야겠네요

> 객체의 관점에서 데이터를 관리한다는 것이 어떤것인지?
저는 데이터를 관리한다. 라는 의미를 객체의 상태라고 받아 드렸어요 객체만이 가질 수 있는 상태요

> 제 생각에는 결국 객체는 어쩔수 없이 의존을 가지게 되고 일부 의존에 따라 '스스로' 관리가 100% 되지는 않을것 같다는 생각인데요. 
이 부분은 '스스로'가 객체의 상태만 관리한다고 가정하면 충분히 가능하다고 보는 입장입니다. 객체를 의존하는건 그 객체의 상태를 가지는게 아닌 
그저 협력하는 객체정도 라고 생각이 됩니다.

**Comment by platanus-kr** [comment]
@zinzoddari > 값을 외부에서 주입받는것이 아닌 메시지를 통해서 스스로의 상태를 바꾸는것 

@midcondria > (JPA의 경우) 엔티티에서 스스로 상태를 바꾸는 메소드를 만들면 외부의 변경으로부터 자유롭다.
