### ISSUE TITLE
[7주차] 하향식 접근법과 설계

### ISSUE THREAD

**Issue by platanus-kr** [IDIOT-s/object-book-study#51]
이번주는 하향식 접근법에 대한 이야기를 다루네요. 설계 관점에서 하향식 접근은 모든 프로세스를 하나의 양식으로 강제하는 경향이 있기 때문에 '관심사의 분리' 측면에서 좋지 않다고 합니다. 생각해보면 스프링의 MVC 패턴도 사용자 인터페이스를 담당하는 컨트롤러 레이어와 비즈니스를 담당하는 서비스 레이어가 굳이 나눠져 있는 이유도 여기서 찾을 수 있을 것 같네요.

그러면서 하향식 접근이 적절한 영역에 대해서 설계가 아니라 알고리즘을 최적화 하는데 유용하다고 합니다. 실제로 4장의 코드 리펙토링 과정을 통해서 낮은 결합도와 캡슐화를 위해 어떻게 최적화 했는지 설명했었지요. 

오랜만에 부담없이 읽었네요.
금주도 수고 많으셨습니다.

**Comment by beng9re** [comment]
> 하향식 접근이 적절한 영역에 대해서 설계가 아니라 알고리즘을 최적화 하는데 유용하다고 합니다.

저도 이부분에서 Util 성 클래스들은 하향식 접근이 적절하지 않을까? 라는 생각이 들었어요

수고 많으셨습니다!
