### ISSUE TITLE
[7주차] 객체 분해하기 후기

### ISSUE THREAD

**Issue by ch200203** [IDIOT-s/object-book-study#52]
갑자기 예시코드로 루비가 튀어나와서 살짝 당황한 주차였습니다 🤣

최근 프로그래밍 언어의 추상화 매커니즘에는 **프로시저 추상화 ( procedure abstraction )** 와 **데이터 추상화 ( data abstraction )** 두가지가 존재합니다.

**프로시저 추상화**
소프트웨어가 무엇을 해야 하는지를 추상화한다.  (행위)

**데이터 추상화** 
소프트웨어가 무엇을 알아야 하는지를 추상화한다. (데이터)

기능분해의 관점에서 추상화 단위는 **프로시저**이며 시스템은 프로시저를 기반으로 분해합니다.
- 저는 이부분을 행위를 기반으로 기능 단위를 분류하여 추상화 한다고 이해하였어요.

하향식 접근 방법에 대해서는 다양한 의견이 있지만, 작은 단위의 기능, 알고리즘 그리고 작은 단위에서의 리팩토링에서는 하향식 접근 방법이 오히려 더 좋다고 생각합니다.
- 개발 시작부터 전체 시스템의 구조를 먼저 고려하고 시작을 하기 때문에, 전체 시스템에 큰 영향을 미치지 않음.
- 해결해야하는 문제를 작은 문제로 쪼개어 해결하기 때문에 생각의 방향성에 안정감을 제공.
-> 위 장점을 바탕으로 세부 구현을 리팩토링 할 때, 전체적인 구조에 대한 이해를 바탕으로 안정감있는 리팩토링이 가능하다고 생각합니다.

=> ***이부분에 대한 여러분들의 생각은 어떤지 궁금해요.***

데이터 추상화, 추상데이터 타입 그리고 클래는 정말 흥미롭게 읽었습니다.

제가 이해한 바로는 
클래스와 추상데이터 타입은 서로 다른 패러다임에서의 핵심 요소 같아요.

클래스는 **객체지향 프로그래밍**의 핵심 요소이고, 추상 데이터 타입은 **객체 기반 프로그래밍의** 핵심 요소로 생각합니다.

**클래스 (OOP)**
- 데이터와 메서드를 캡슐화
- 상속을 통해 코드 재사용성과 확장성을 제공
- 다형성을 통해 다양한 타입의 객체를 동일한 인터페이스로 처리 가능

**추상 데이터 타입 (Object-Based)**
- 데이터 타입의 인터페이스에 중점을 두고, 구현은 숨깁니다.
- 상속과 다형성에 중점을 두지 않고, 데이터와 그 데이터에 적용되는 오퍼레이션에 중점
- 구현의 세부 사항은 외부에 노출되지 않으며, 사용자는 제공된 인터페이스만을 통해 작업을 수행

```java
public interface UserService {
    User getUserById(Long id);
}

@Service
public class UserServiceImpl implements UserService {
    @Override
    public User getUserById(Long id) {
        // 사용자 조회 로직
    }
}

@RestController
public class UserController {
    private final UserService userService;

    public UserController(UserService userService) {
        this.userService = userService;
    }

    @GetMapping("/users/{id}")
    public ResponseEntity<User> getUser(@PathVariable Long id) {
        User user = userService.getUserById(id);
        return ResponseEntity.ok(user);
    }
}

public interface UserRepository extends JpaRepository<User, Long> {
    // 사용자 이름으로 조회
    User findByName(String name);
}
```

둘중 뭐가 더 좋은 방법이라기 보다는, 각각에 알맞은 패러다임을 선택해야 한다고 생각합니다.
예를들어 Spring 에서는 서비스 - 컨트롤러는 OOP를 통해서 구현되고, 리포지토리는 객체 기반을 통해서 구현된다고 생각해요. 그리고 이것이 스프링의 큰 장점이라고 생각합니다.

**Comment by beng9re** [comment]
> 개발 시작부터 전체 시스템의 구조를 먼저 고려하고 시작을 하기 때문에, 전체 시스템에 큰 영향을 미치지 않음.
> 해결해야하는 문제를 작은 문제로 쪼개어 해결하기 때문에 생각의 방향성에 안정감을 제공.
-> 위 장점을 바탕으로 세부 구현을 리팩토링 할 때, 전체적인 구조에 대한 이해를 바탕으로 안정감있는 리팩토링이 가능하다고 생각합니다.
=> 이부분에 대한 여러분들의 생각은 어떤지 궁금해요.

저도 이 부분에 있어서 Input과 output이 명확한 케이스에서는 하향식 구조가 적절하다고 생각합니다. 말씀하신 알고리즘이 대표적인 예시겠지요.
그리고 적은 범위에서도 동감합니다.


근데, 
저희의 비지니스는 생각보다 복잡하고 전체구조를 알기에는 너무나 힘들다고 생각해요. 
또한,
하향식 호출하는쪽이 하위 호출이 정해져 있어서 (잘 알고 있어서) 서로간의 강하게 의존이 되어 상위, 하위간에 영향을 주어서 변경을 초래하게 되는것 같습니다.
