### ISSUE TITLE
[8주차] 적절한 의존성

### ISSUE THREAD

**Issue by platanus-kr** [IDIOT-s/object-book-study#55]
이번주는 객체끼리 협력할때 의존이 어떻게 발생하고 발생하는 각 시나리오에 대해 어떤 의존이 적절하고 부적절한지 이야기하는 챕터였네요. 저도 '의존은 원래 자연스러운거다' 까지만 알고 있고 구체적으로 어떤 의존이 자연스러운건지 설명하라 그러면 사실 대답할 수 없는 상태였는데요.. 퍼블릭 인터페이스를 통한 노출의 **명시적 의존성**과 구체를 통해 노출되는 **숨겨진 의존성**이라는 키워드를 통해 드디어 명쾌한 해답을 얻을 수 있었다고 개인적으로 생각합니다.

또한 이번 장에서도 지난장 처럼 객체 내부가 아닌 클라이언트를 통해 의존을 분리시키는 행위들이 계속 나오고 있네요.

오랜만에 개인적으로 궁금한게 있는데, p278~p279에 나오는 `OverlappedDiscountPolicy`는 혹시 일급컬랙션에 해당할까요?

```java
public class OverlappedDiscountPolicy extends DiscountPolicy {
    private List<DiscountPolicy> discountPolicies = new ArrayList<>();

    public OverlappedDiscountPolicy(DiscountPolicy ... discountPolicies) {
        this.discountPolicies = Arrays.asList(discountPolicies);
    }

    @Override
    protected Money getDiscountAmount(Screening screening) {
        Money result = Money.ZERO;
        for(DiscountPolicy each : discountPolicies) {
            result = result.plus(each.calculateDiscountAmount(screening));
        }
        return result;
    }
}

```

(맴버가 저거 하나라는 것을 가정했을때) 일급컬랙션의 역할을 하는것 같다는 생각이 드네요. 여러분들의 의견이 궁금합니다.

금주도 수고 많으셨습니다. 진호님 클래스에서 만나요 🤗

**Comment by yeongsik** [comment]
민철님 덕분에 이번에 1급 컬렉션에 대해서 공부를 해보았습니다.
일급 컬렉션이란 컬렉션을 래핑하면서 그 외 다른 멤버 변수가 없는 상태라고 합니다.

출처 글에서 일급컬렉션의 이점을 설명하는데 OverlappedDiscountPolicy 클래스가 해당 이점에 부합하는지 적어봤습니당

#### 일급 컬렉션의 이점
1. 비즈니스에 종속적인 자료구조
할인 정책에 대한 비즈니스 요구사항 조건이 별 게 없어서 OverlappedDiscountPolicy 가 비즈니스에 종속적인 자료구조라 볼 수 있지 않을까여?
    
2. Collection의 불변성을 보장
discountPolicies에 final은 없지만 생성자 이외에 discountPolicies에 접근하는 메서드가 따로 없기에 불변성이 보장한다고 봅니당 
    
3. 상태와 행위를 한 곳에서 관리
discountPolicies에 대한 할인 금액 계산하는 메서드를 갖고 있기 떄문에 상태와 행위를 한곳에서 관리한다고 볼 수 있을 것 같아여
    
4. 이름이 있는 컬렉션
OverlappedDiscountPolicy가 의미를 가진 이름 있는 컬렉션이라고 봅니당

내일 일급컬렉션에 대해서 한번 이야기 해도 좋을 것 같습니다 :)

출처 : https://jojoldu.tistory.com/412

**Comment by beng9re** [comment]
@yeongsik 님이 설명해주셨던것 처럼 딱 저부분 만 봤을대는 일급 컬랙션이라고 봐도 무방할꺼 같지만 걱정이 되는 부분은 

상속을 통한 구현을 사용하고 있는데 `extends DiscountPolicy` 이 부분이 살짝 걸리네요. 뭔가 부모에 따라서 늬앙스가 달라질꺼 같다는 느낌입니다.
