### ISSUE TITLE
[8주차] 관습적인 Service 인터페이스와 ServiceImpl 클래스

### ISSUE THREAD

**Issue by yeongsik** [IDIOT-s/object-book-study#56]
추상화에 의존하는게 좋다는 부분에서 무분별한 Service 인터페이스와 ServiceImpl이 떠올랐는데
Service가 하나면 구체 Service 클래스 쓰시나요 아니면 한쌍의 Service 인터페이스와 ServiceImpl를 사용하시나요? 궁금합니다.

그리고 저는 Service 인터페이스를 여러 구체 클래스로 구현해서 사용해본 경험이 없는데 있으신 분들의 경험을 듣고 싶습니당

**Comment by yeongsik** [comment]
@beng9re 
답변 감사합니다.

관련 링크를 읽어보고 제가 이해한 내용인데 제대로 이해한게 맞을까요?? 
예전에는 JDK 다이나믹 프록시만 스프링 AOP에서 사용해서 인터페이스 - 구현 클래스로만 사용할 수 밖에 없었는데 CGLIB에서 구현 클래스도 프록시를 만들 수 있게 됨 스프링이 CGLIB를 채택하면서 구현클래스로만으로 생성할 수 있게 되었지만 과거에 사용했던 관습이 남아 있어서 Service 인터페이스 - ServiceImpl 구현 클래스 관계가 많이 사용되고 있음

**Comment by beng9re** [comment]
네네 맞습니다. 이게 관습이 패턴처럼쓰게 되는거죠. 

아니면 해당 프로젝트기준에서 JDK 다이나믹프록시로 바꿔서 쓴다면
