### ISSUE TITLE
[8주차] 의존성 관리하기

### ISSUE THREAD

**Issue by ch200203** [IDIOT-s/object-book-study#58]
##  의존성 이해하기
- 실행 시점: 의존하는 객체가 정상적으로 동작하기 위해서는 실행 시에 의존 대상 객체가 반드시 존재
- 구현 시점: 의존 대상 객체가 변경될 경우 의존하는 객체도 함께 변경

### 의존성은 변경에 취약
- 설계과 관련된 대부분의 용어들이 변경과 관련이 있습니다.
-> 의존성 역시 변경과 관련이 있음!
- 두 요소 사이의 의존성은 의존되는 요소가 변경될 때 의존하는 요소도 함께 변경될 수 있다.
- 따라서 의존성은 변경에 의한 영향의 전파가능성 -> 의존관계에 있는 객체들이 우수수 수정...

### ***런타임 의존성과 컴파일타임 의존성***
그럼 Spring에서 `객체 주입(@Autowired)` 은 런타임 의존성일까? 컴파일타임 의존성일까요?
-> @Autowired는 런타임 의존성에 포함 
 컴파일타임에는 인터페이스나 추상 클래스에 대한 의존성만 존재하며, 구체적인 클래스 타입은 명시되지 않습니다
런타임에 Spring IoC 컨테이너가 @Autowired를 해석하여 실제 구현체를 찾고 -> 해당 Bean의 인스턴스를 생성한 후, 의존하는 객체에 주입하는 과정을 거침
즉, 컴파일타임에 정의된 인터페이스나 추상 클래스에 대한 의존성을 **런타임에 구체적인 구현**으로 연결해주는 메커니즘이라고 합니다.

=> 컴파일과 런타임 의존성은 각각 언제 사용하는게 가장 좋을까요?
컴파일 타임 의존성은 API와 라이브러리, 유틸성 과 같이 변경가능성이 거의 없는 안정적인 상황에서  사용하기 좋을 것 같다고 생각해요!
반면에 런타임 의존성은 유연하고 변경이 용이한 비즈니스 코드를 구현하는데 사용하면 좋겠다 라는 생각이 들었습니다!

### 추상화에 의존하라
아래쪽으로 갈수록 결합도가 느슨해짐
- 구체 클래스 의존성 -> 추상 클래스 의존성 -> 인터페이스 의존성

### new는 해롭다
그럼 해로운 상황들을 해결하기 위해서 인스턴스를 생성하는 로직과 생성된 인스턴스를 사용하는 로직을 분리하라고 하는데
이걸 의존성 주입이나, 팩토리 메서드 패턴으로 해결 하면 좋을 것 같다고 생각했습니다..!
여러분은 어떻게 생각하실까요?

**Comment by yeongsik** [comment]
이번 주에도 읽으시느라 고생 많으셨습니다. 철환님 ㅎㅎ

정리해주신 글을 읽으면서 다시 한번 책 내용이 리마인드 됩니다.

컴파일과 런타임 의존성은 각각 언제 사용하는게 가장 좋을까요?
=> 철환님 생각이 맞다고 생각합니다. 책에서도 new 사용함에 있어서 표준 클래스는 괜찮다고 이야기를 하고 있어서
런타임 의존성은 변경이 많은 부분에서 활용하는게 맞다라는 생각이 들었습니다.
 
저도 new는 해롭다를 읽으면서 
개발자가 비즈니스 로직에만 집중할 수 있도록 의존성을 주입하는 담당을 스프링이 해주고 있다는 사실이 다시 한번 떠올랐던 것 같습니다.
