### ISSUE TITLE
[1주차] 인상 깊었던 점 : 객체의 자율성 그리고 트레이드 오프

### ISSUE THREAD

**Issue by yeongsik** [IDIOT-s/object-book-study#6]
서론과 1장을 읽고 느낀점은 프로그래밍엔 은총알은 없고, 여러 방법과 상황 속에서 합리적인 트레이드 오프를 선택해야 한다는 점이었습니다. 아직 경험과 실력이 부족한 터라 이 책을 읽으며 합리적인 트레이드 오프를 위한 방법론(논리)들을 배울 수 있겠다 싶었습니다.

1장에서 인상 깊은 부분은 객체의 자율성이었습니다. 객체가 갖고 있는 데이터는 객체가 처리해야 하며 구현 부분은 캡슐화, 외부와 협력 부분은 인터페이스로 진행해야 한다고 말하고 있습니다. 이 부분을 읽으며 객체지향의 첫번째 단계는 각 객체의 자율성을 생각하면서 상황에 따른 트레이드 오프가 아닐까라는 생각이 들었습니다.

p.s
1장의 간단한 예제 코드에서도 트레이드 오프에 대한 토론이 발생하는데 프로젝트나 현업에서 겪으신 트레이드 오프에 대한 토론 경험들이 개인적으로 궁금합니다.

**Comment by platanus-kr** [comment]
이번주 호스트라서 답변을 달아야하니 일단 달아봅니다만..
제 경우는 트레이드 오프는 객체간 책임을 어떻게 할거냐 보다는 '쿼리로 하면 되는거 왜 자바로 하느냐' 는 쿠사리 였습니다 😇

**Comment by beng9re** [comment]
허락보다 용서가 쉽다!
