### ISSUE TITLE
[8주차] 그렇다면 의존하는 객체는 어디에서 생성하면 좋을까요?

### ISSUE THREAD

**Issue by beng9re** [IDIOT-s/object-book-study#60]
이번장에서 의존성을 다루는 방법에 대해서 설명해주었던거 같아요. 
setter, 생성자, 필드, 런타임 의존성을 권고등...

근데, 의존성 관리를 위해 생성자 주입을 통해 각 객체를 생성을 한다고 가정하고,
예를 들어 1번 객체 -> 2번 객체 -> 3번 객체 -> 4번 객체 있다고 보면

최상위 객체에서 1번, 2번, 3번, 4번에 필요한 객체들을 생성하고 다가지고 있는 형태(다 알고 있는 형태)가 나온다고 생각이 되는데 
이때야 말로 274p에 나오는 `가끔은 생성해도 무방하다` 말에 의해서 중간에서 직접 생성해도 될꺼 같다.라는 생각이 들었어요 

생각이 깊어지니 그럼 어느정도 단계에서 객체를 생성하면 좋을까요?

**Comment by yeongsik** [comment]
상황이 바로 이해가 되지 않아서 코드로 작성해봤습니다 ㅎㅎ

```
public class TopObject {
    public static void main(String[] args) {
        ObjectA objectA = new ObjectA(new ObjectB(new ObjectC(new ObjectD())));
    }
}
```

병휘님이 말씀해주신 상황이 이게 맞을까여??
만약에 중간에 직접 생성한다는 이야기는 최상위 객체에서 책임을 다아는 것보다 2,3번 객체에서 책임을 아는 것이 낫다는 의미일까요?
그럼 변경될 때 사이드 이펙트가 최상위 객체까지 전이 되지 않고, 중간 단계에서 끊어질 것으로 보이네요!

스프링을 사용하면서 의존성에 대한 고민을 깊게 한 적이 없는데 해당 질문 다같이 이야기해보면 좋을 것 같습니다!

**Comment by beng9re** [comment]
@yeongsik 오 딱 그 상황입니다
