### ISSUE TITLE
[9주차] 복잡한 설계와 유연한 설계

### ISSUE THREAD

**Issue by ch200203** [IDIOT-s/object-book-study#63]
**유연한 설계 = 복잡한 설계**

객체지향 패러다임에서는 상위 수준의 모듈과 하위 수준의 모듈 두가지 모두 **추상화**에 의존하는 구조로 만들어지게 됩니다.
변경에 대비하기 위한 설계를 하기위해서 우리는 억지로 복잡한 설계방식을 택하게 됩니다.

> 아직 얼나지 않은 변경은 변경이 아니다.

계속해서 책에서 언급되듯 당장 필요하지 않은 변경을 예상하며 유연한 설계를 지향하는 것은 불필요한 복잡한 설계를 낳을 수 도 있습니다.
최근 몇가지의 미션과 과제 그리고 새로운 프로젝트를 들어가면서 프로젝트 구조에 대한 설계에 대해서 많은 고민을 할 일이 생겼습니다.

책에서 의도한대로 어느정도 객체의 책임을 생각하려하고 도메인에 대해서 추상적으로 설계하고 필요한 부분만 객체지향적으로 작성해주려고 노력하였습니다만... 

저도 모르게 도메인 데이터를 먼저 설계하게 되고, 복잡한 설계방식을 택하게 되더라구요.
그래서 새로운 고민을 하게 되었는데 코드를 읽는 사람의 주체가 과연 누구일까라는 관점에서 바라볼 때 
**불필요한 유연성은 불필요한 복잡성을 낳는다** 라는 말이 더 잘 와닿았습니다.

단순하고 명확한 해법이 지금 괜찮아보인다면 그것도 괜찮다고 생각합니다.
너무 과도한 유연성은 코드를 읽는 사람들이 그 복잡함을 감수하고 또 금방 이해가 될 수 있을 때만 그 가치가 있는 것 같습니다.
다만, 재사용성이나 확장이 정말 필요한 경우에는 객체지향 페러다임을 적용시키는게 맞지 않을까 라는 생각을 이번에도 해봅니다.

개인적인 여담으로... 9장의 내용을 제대로 이해하려면 아직 멀었다라는 생각이 드는 주차였습니다.

**Comment by platanus-kr** [comment]
저도 이번에 9장 읽으면서 설계가 유연해질수록 코드가 복잡해진다는 것을 보고  "오버엔지니어링 하지마라" 하는 주제가 관통하는것이 아닌가 싶었습니다. '그땐 맞고 지금은 아닌 설계'의 반대 급부로 미래에 맞을것 같은 설계를 미리 할 필요가 없는것 아닐까? 하는 생각도 드네요.
금주도 수고 많으셨습니다.
