### ISSUE TITLE
[9주차] 의존성 역전의 의미와 객체지향은 실제 세계의 모방이 아니다 부분이 인상 깊었습니다.

### ISSUE THREAD

**Issue by yeongsik** [IDIOT-s/object-book-study#66]
9장은 8장에서 이야기 했던 의존성에 대해서 어떻게 하면 유연하게 OCP를 지키면서 코드를 작성할 수 있는지
 그리고 객체지향적인 설계가 유연하지 않을 경우 pure fabrication을 사용해서 보완해야한다는 부분이 인상깊었습니다.

의존성 역전에서 "역전"에 의미가 무엇인지 궁금했던 적이 있었는데 그 때 답변이 9장을 읽으면서 다시 리마인드하게 되었습니다. 

또한 객체지향적으로 설계를 해도 높은 결합도와 응집도가 낮다면 보완책을 사용해야 한다는 내용과 그 예시로 현실 세계에서도 자연으로만 이루어져있지 않고, 도시에 있는 인공물들이 현실 세계를 보완해주고 있다는 부분이 인상 깊었고, 예시를 통한 이해도 빠르게 되었습니다.
결국 유연한 코드를 작성하기 위해선 디자인 패턴과 같은 pure fabrication 방법들을 알고 있어야 한다는 것을 깨달았던 장입니다.

**Comment by platanus-kr** [comment]
책 내내 '객체'에 대해서만 집중하다 갑자기 순수한 생성물에 대한 내용이 나오니까 약간 당황스러웠지만 생각해보면 어플리케이션을 구성하는 코드들이 도메인 비즈니스뿐만 아니라 프레임워크나 미들웨어를 다루는 부분도 상당히 있다고 생각히 들었으요.
금주도 고생 많으셨습니다.
