### ISSUE TITLE
[9주차] 요약

### ISSUE THREAD

**Issue by unknownKade** [IDIOT-s/object-book-study#67]
## 개방-폐쇄 원칙(OCP)
개방-폐쇄 원칙은 객체는 확장에 열려 있으면서 수정에는 닫혀있어야 한다는 원칙이다.
이 원칙은 모순적이지만 사실상 가리키는 것은, 코드에서 명시적으로 협력하는 관계를 실행 시 협력하는 런타임 의존성으로 대체하는 것이다. 이는 추상화를 통해서 이룬다. 변경되지 않는 핵심을 추상화하고 수정되는 문맥으로 확장을 한다.

## 생성과 사용 분리
추상화에 의존하기 위해서는 구체 클래스의 인스턴스를 의존하는 객체 내부에서 생성해서는 안된다. 생성과 사용은 다른 책임이기 때문이다. 하지만 추상화의 구체 클래스 생성을 따로 특정 도메인에 책임을 할당하기 어렵다. 도메인이 아니어도 설계의 문제를 해결하기 위한 객체를 구현하여 이 책임을 할당할 수 있다. 이런 컨텍스트를 담당할 다른 클라이언트 혹은 팩토리를 써서 두 책임을 분산 시킨다.

## 의존성 주입
생성을 직접하지 않기 때문에 의존성 주입으로 외부에서 생성된 인스턴스를 전달 받는다. 의존성을 주입하는 방법은 세 가지 있다.
- 생성자 주입 : 객체 생성 시점에서 생성자 사용
- setter 주입 : 해당 객체의 setter로 주입
- 메서드 주입 : 메서드 인자로 주입
#### Service Locator 패턴
의존성 주입 대신 객체들을 보관하는 Service Locator 클래스를 따로 두어서 해당 클래스에게 직접 요청을 하는 방법도 있다. 하지만 이럴 경우 의존성을 감추어 개발자가 런타임 의존성을 알기 어렵게 된다.

## 의존성 역전 원칙
상위 수준의 클래스가 협력관계에서 의사결정을 하는 본질을 담고 있다. 만약 구체적인 사항이 추상화에 의존하게 된다면 상위 수준의 클래스가 하위 수준의 클래스에 의존하게 된다. 디테일 때문에 의사결정이 영향되는 이상한 방향이다. 둘 다 추상화에 의존해야 기존 프로그래밍의 의존성의 방향(상위 클래스가 하위에 의존)을 역전할 수 있다.

**Comment by platanus-kr** [comment]
DIP의 원칙인 "고수준 모듈은 저수준 모듈에 의존하면 안 된다. 둘 다 추상화에 의존해야 한다" 에 대해서 좋은 예시였던것 같습니다. 도메인 엔티티에서 DTO를 알 필요가 없는것처럼요!

금주도 고생 많으셨습니다!
