### ISSUE TITLE
[10주차] 상속의 주의점 및 후기 

### ISSUE THREAD

**Issue by beng9re** [IDIOT-s/object-book-study#68]
10장은 DRY(Don't Repeat Yourself) 원칙을 시작으로 상속에 대한 내용을 담았습니다.

상속(extends)에 대한 내용을 설명하면서 자식 클래스가 부모와의 결합도가 높아져서 변경의 영향이 큰게 된다는 사실을 언급해주고 있네요.
그리고 Java에서 잘못된 예시 (Stack, Properties)를 알려주었어요

상속을 사용했을때에 대한 주의점을 나름 대로 책에 내용에서 정리를 해봤습니다.
* super. 참조를 한 선언 지양
* 상속을 도입하기 전에는 구현에 대한 내용을 인지해야 함으로 주석화(문서화)하기.
* 부모 클래스의 추상화를 의존하도록 하며 자식의 공통 코드들을 부모 클래스로 추상화 한다.

이번장은 딱히 궁금한점이나 그런게 없었네여, 
상속이 캡슐화를 깨지는것은 많이 들어서 알았고 extends를 통한 구현은 생각을 꼭 필요한지 생각해봐야겠습니다. 
11장의 합성에 대한 내용이 궁금해지네요

**Comment by JHwan96** [comment]
저도 extends의 위험성에 대해서 자주 듣다보니 상속를 통한 구현에 대해서 조금 꺼려지는 것 같네요.
그리고 저번에 extends는 왜 다중 상속이 안되는지 찾아보면서 상속 보단 합성을 써야겠다고 생각했습니다:) 
고생 많으셨습니다!
