### ISSUE TITLE
[10주차] 상속과 코드 재사용 후기

### ISSUE THREAD

**Issue by ch200203** [IDIOT-s/object-book-study#69]
드디어 읽을만한 회차가 나왔던것 같습니다.

상속을 이용하여 코드를 `재사용` 하는 행위는 높은 결합도를 가진다는 의미에 대해서 다시 되짚어 볼 수 있었습니다.

>  상속은 퍼블릭 인터페이스(public interface)를 재사용하는 것이 아니라, “코드(CODE)”를 재사용하는 것이다.
>  자식 클래스는 부모 클래스의 내부 구현을 자세히 알아야 한다. 왜냐하면 부모 클래스의 메서드를 재정의(Override) 하려면 부모 클래스에서 어떤 상태와 행동을 가지고 있고 어떻게 구현하고 있는지 알아야 한다. 
>  그래서 상속은 퍼블릭 인터페이스(Public Interface)를 재사용하는 것이 아니라, **코드 자체를** 재사용하는 것이다. 이러한 특징 때문에 자식 클래스는 부모 클래스에 대해서 알아야 하는 지식의 수준이 높아야 한다. 다른 말로, 캡슐화는 깨졌고 의존성은 높아지고 객체 간의 **결합도**가 강해진다.

이 부분이 핵심이라고 생각합니다.

그에 대한예시로 `java.util.Properties`와 `java.util.Stack`을 들어 설명을 잘 해주어서 되짚어 볼 수 있는 좋은 기회가 되었습니다.

이펙티브 자바에서도 

> 상속을 위한 설계와 문서를 갖추거나, 그럴 수 없다면 상속을 금지하라

라고 언급을 하고 있는데요.

상속이 코드 `재사용`이라는 측면에서 매우 강력한 도구인것은 맞으나, 잘못 사용될 경우 프로그램에 심각한 오류를 가져올 수 있는 녀석입니다.
극단적으로는 이렇게 사용 될 바에는 그냥 중복코드를 사용하는게 더 낫다고 생각합니다.

최근 개발하는 코드를 보면 구현에 대한 관심을 분리하여 결합도, 의존도를 낮추는 형태를 취하고 있습니다.
인터페이스를 사용하게 되면 코드의 재사용이라는 측면에서만 볼 때는, 많은 중복코드를 야기하여 상속과는 반대되지만. 

이로인해 의존도를 낮추고, 유연함을 증가시켜 단순하게 코드 재사용으로 얻는 이득보다 많다고 생각됩니다.
따라서, DRY 원칙을 조금은 다른 관점에서 생각해 볼 필요성이 있지 않나 라고 저는 생각합니다. :)

**Comment by JHwan96** [comment]
10장의 처음에서는 DRY원칙에 대해서 말하고 있는데, 철환님 말씀대로 합성에서는 결국 중복을 허용할 수 밖에 없지 않나라는 생각을 다시 하게 되었습니다 :) 저도 상속 보다는 합성을 지향하는 것이 좋다고 누차 들어왔는데, 다음 장에서 과연 어떻게 설명할지 궁금해지네요
고생하셨습니다 😁
