### ISSUE TITLE
[1주차] 1장 정리 및 질문..?

### ISSUE THREAD

**Issue by JHwan96** [IDIOT-s/object-book-study#7]
- 응집도와 결합도에 대해서 이론적인 지식만 알고 실제 어떤 상황에서 사용되는지는 잘 몰랐던 것 같습니다. 캡슐화, 인터페이스의 활용을 통해 객체가 자율성을 가지고 스스로 자신의 데이터를 책임진다는 것을 통해 좀 더 실제적으로 응집도와 결합도에 대해 이해가 된 것 같습니다.
- ‘의존성이 `Theater`에서 제거되는 대신 `TicketSeller`로 추가되는 것을 적절한 트레이드오프라고 설명하는 것’ (p.27)을 처음에는 의문을 가졌으나 책임의 분배라는 점에서 합당하다는 생각이 들었습니다.
- 기능을 설계하는 방법은 여러가지일 수 있고 그중에 제일 트레이드오프가 적은 것을 선택하는 것이 좋은 방향이라는 것을 알게 되었습니다. 
  - 물론 트레이드오프가 제일 적도록 설계하는 방법이 어떤 것인지는 좀 더 알아나가야 할 것 같습니다..
- 가방과 매표소를 하나의 사람처럼 대하는 것(p 29~)이 맞는가에 대한 의문을 가질 즈음, 모든 객체가 자율성을 가져야 한다는 글을 통해 스스로 갖혀 있는 문제에 대해서 알게 되었습니다.

이번 장을 통해 현실 세계의 대상을 중심으로 코드를 생각했던 것에서 벗어나, 각 객체가 자율성을 가지고 있는 코드를 짤 수 있도록 노력해봐야겠다는 생각을 했습니다.

**뻘질문**
1. 적절한 객체에 적절한 책임을 할당에서 적절함의 기준을 다들 어떻게 잡으시나요
2. 설계할 때 있어서 어떤 것을 더 중요하게 바라보는지 궁금합니다. (책에서의 `Audience`와 `TicketOffice` 간의 트레이드오프 [p.33])

p.s 글 중에서 의문이 들거나 이상한 것이 있다 생각하시면 여러분들이 맞는 것이기 때문에 적절한 피드백 부탁드립니다 :)

**Comment by platanus-kr** [comment]
금주도 수고 많으셨습니다.
저 역시 매번 이정도면 됐겠지 하는데 설계는 볼때마다 새롭고 어렵습니다 😣 
질문에 대해 답변을 드리자면..

1. 1장에서는 메소드의 분리(또는 이동)만 두고 이야기하지만 뒤에 객체를 어떻게 조합하고 분리할 것인가에 대한 이야기가 나오지 않을까요..?
2. 이건 제 생각인데 '`TicketOffice`가 굳이 `Audience`를 알아야 하는가?' 의 결과물이라고 생각합니다.

**Comment by platanus-kr** [comment]
@zinzoddari  메시지를 받을 준비가 된 친구는 곧 객체행
@ch200203  맴버가 딱 하나의 역할만 할때는 객체로 뽑을 필요가 있을까? 객체를 새로 뽑는 변경은 라이브 프로덕트에서 비용이 큰데? (ex. 엔티티)
@platanus-kr  이 책에서 설명하는 것이 바로 '변경 가능한 설계를 하고, 유지보수 가능한 설계를 하자' 라는 목표를 가지고 있다
@midcondria  변경 가능성이 높고 자주 건드리는 경우에는 분리를 하고, 아닐때는 필드로 두면 될 것 같다.
@zinzoddari  꼭 엔티티로 뽑아야 할 필요가 있을까?
@beng9re  분리 하는 기준은 판단하기 어렵지만, 2개 이상 늘어나면 객체로 분리하는게 좋을것 같다. (시니어의 말을 듣자)
