### ISSUE TITLE
[11주차] 추상클래스는 중복된 절차를 고정하는데 쓰이면 좋지 않을까요?

### ISSUE THREAD

**Issue by beng9re** [IDIOT-s/object-book-study#74]
이번장에 합성을 사용하는 방법에 대해서 코드와 함께 제공해주었네요.

### 후기 

합성이 행동을 인터페이스로 추상화하고 그것을 객체에서 가진 형태로 조합하는걸로 이해를 했는데
이 부분이 저희가 평소에 작성하는 DI와 같다고 생각이 들었어요 
이렇게 생각하다보니 합성에 대해서 위화감이 덜 했던거 같아요. 

```java 
public class Phone {
	private RatePolicy ratePolicy: // 행동을 가진다!

	private List<Call〉 calls= new ArrayList();

	public List<Call> getCalls() {
		return Collections.unmodifiableList(calls);
	}

	public Money calculateree() {
		return ratepolicy.calculateFee(this);
	}
} 
```
> 폰이 ratePolicy라는 행동을 가진다

믹스인은 솔직히 왜 쓰는지는 잘 이해가 안 되었답니다.
Java로 걍 디폴트 메서드메서드 구현한 Interface를 다중으로 implements한건가? 싶어요

### 상속의 쓰임새?
내용을 보면서 상속은 그러면 쓰면 죄악일까? 라는 생각에 한번 고민을 해보았는데 
이미 예제에서도 상속을 사용하고 있더라구요.

```java
public abstract class AdditionalRatePolicy implements RatePolicy {
	private Ratepolicy next;

	public AdditionalRatePolicy(RatePolicy next) {
		this.next = next;
	}


	@Override
	public Money calculateFee(Phone phone) {
		Money fee = next.calculateree(phone);  // 계산을 하고
		return afterCalculated(fee);  // 다음 계산을 수행한다.
	}

	abstract protected Money afterCalculated(Money fee);
}

```

위에 코드를 보면 `calculateFee` 라는 퍼블릭 메서드에서 `1. 계산을 하고`, `2. 다음 계산을 한다` 라는 절차를 고정 해놓고
`afterCalculated`를 추상화 함으로써 
상속 받는 객체에서는 같은 절차를 가지고  `다음 계산을 한다`라는 행동에 대한 것을 자세한 내용은 동적으로 구현하겠끔 설계가 되어 있어요.
이를 통해 느낀건 상속을 통해 중복된 절차를 고정하는데 좋겠구나 라는 생각이 들었네요.

**Comment by ch200203** [comment]
믹스인은 자바에서 완벽하게 구현을 지원하지 않는 것 같아요!
자바에서는 그냥 interface에서 default 로 구현해 놓고 implements를 여러개 한 것을 믹스인으로 취급하는 것 같다는 생각입니다.

믹스인은 `다이아몬드 문제`가 발생할 수 있는 언어들을 위해 존재 하는 패턴이라고 생각됩니다.
자바는 다중상속을 지원하지 않기 때문에 애초에 이 문제가 발생하지 않아 굳이 고려하지 않았던것 같아요.

Repository 에 믹스인을 활용한 예시인데 참고해봐도 좋을 것 같아요!
https://hyune-c.tistory.com/50 

상속은 Spring 에서 `WebConfig`나,`WebSecurityConfigurerAdapter` 등등 이 있었던걸로 기억이 나네요.
물론 `WebSecurityConfigurerAdapter`는 이제 Deprecated 되었지만...ㅠ

읽으시느라 너무 고생 많으셨습니다 월요일에 봐요!
