### ISSUE TITLE
[13주차] 그렇다면 추상클래스는 어떤가요

### ISSUE THREAD

**Issue by unknownKade** [IDIOT-s/object-book-study#82]
## 요약
이번 주 장은 그간 상속을 어떻게 써야하는지에 대한 얘기를 좀 더 상세히 다뤘습니다. 코드 재사용성을 목적으로 한 상속은 서브 클래싱으로 is -a 관계를 통상적으로 사용되는 언어적 관점으로 구현하면 상속이 객체지향의 원칙을 위배하게 되는 점을 예시를 통해 보여줬습니다. 일상적으로 사용되는 is-a 관계는 사물을 분류하는 것인데 행동을 고려하지 않기 때문에 자식을 부모로 대체할 수 없습니다. 리스코프 치환을 위배하게 되는 이런 상속의 실질적인 문제는 코드의 높은 결합도 때문에 변경을 할 경우 부모 자식 모두에게 영향이 간다는 점입니다. 
반면, 권장되는 상속을 타입계층으로 구현하는 경우는 서브타이핑으로 상속을 행동관점에서 분석해서 타이핑하는 것으로 해결할 것을 제시합니다. 행동을 호환 기준으로 타이핑하면 자식을 부모로 호환할 수 있고 클라이언트의 메시지나 요구가 달라져도 인터페이스를 바꾸는 것으로 유연하게 변경할 수 있습니다.

## 후기
타입계층 구현이 그냥 is-a 상속과 어떻게 다른지 예시와 함께 다루어 이해에 도움 되었습니다. 책을 읽기 전에 상속에 대해 오버라이딩 할 것이면 인터페이스를 쓰면 될 것을 굳이 왜 쓰나 생각했는데, 상속을 잘 쓰는 경우라면 같은 것이겠구나 생각하게 되었습니다. 

## 토론거리
추상클래스를 쓰는 분들이 계시다면 이번 장의 내용을 기준으로 봤을때 추상 클래스는 좋은 상속 방법이라고 생각하시는지 궁금합니다.

**Comment by ch200203** [comment]
어떤 조건이냐에 따라 다를 것 같아요.
이번장의 내용의 핵심이 그 내용이라고 생각합니다. 추상클래스를 통해 특정기능을 우리의 입맛에 맞게 재정의해서 사용할 수 있다면 그것도 좋은 방법이라고 생각해요.

아직도 Spring의 많은 부분이 `abstract class`로 선언이 되있는데 대표적으로 `GenericFilterBean` 과 같은 것들이 있을 것 같네요. 
`GenericFilterBean`의 경우는 `Filter` 인터페이스를 구현한 추상화 클래스입니다. 일반적인 필터의 로직을 제공하면서 실제 필터는 `서브 클래스`에서 구현할 수 있게 남겨두게 됩니다. 개발자는 `GenericFilterBean`를 상속 받아 실제 동작을 정의 할 수있고... 또 기본적인 필터의 라이프 사이클은 이미 구현되어 있어 해당부분을 신경쓸 필요가 없고, 또 중복된 코드를 방지할 수 있을 것 같아요.

따라서 일관된 동작의 방식을 강제하고, 필요에 따라 해당 메서드를 오버라이드 하여 커스마이징이 가능한 유연성을 제공하고, 추상클래스를 상속받는 서브 클래스의 상태를 공유하거나, 활요할 수 있게되고, 단일 상속을 통해 계층구조를 단일화(이는 GenericFilterBean과 비슷한 동작을 하는 OncePerRequestFilter 를 참고해도 좋을 것 같아요) 할 수 있어 여전히 상속은 유용한 도구라고 생각이 됩니다.

**Comment by unknownKade** [comment]
서브클래싱의 목적이 코드 재사용인 것이 큰 규모 프로젝트에서 일관성과 계층 구조 잡기 위해서는 그 자체로 순기능인거네요. 예시의 필터 클래스가 많은 도움이 되었습니다.
이번 주도 수고 많으셨습니다!
