### ISSUE TITLE
[13주차] 올바른 상속의 사용법에 대하여

### ISSUE THREAD

**Issue by ch200203** [IDIOT-s/object-book-study#83]
### 후기
이번장은 상속의 올바른 사용법에 대해서 자세하게 설명했던 장 이었던것 같습니다. 그만큼 다형성이 객체지향에서 얼마나 중요한 비중을 차지하고 있는지 느낄 수 있었어요. 상속을 올바르게 사용하기 위해서는 **타입 계층을 구현**하고 `is-a` 관계를 모델링하고, 부모클래스의 타입으로 자식 클래스를 사용가능한(행동 호환성)을 만족할 경우에만 사용이 가능하다고 합니다. 

특히 `is-a` 관계에  있어서도 **클라이언트 관점**에서 만족 시켜야한다고 생각합니다.
위를 만족하지 않는다면 상속이 아니라 **합성**을 통해 클라이언트 관점에서 인터페이스를 분리해서 해결하는게 더 좋은 해결 방안이라고 생각합니다!
앞선 장에서 `Stack`과 `Vector`의 관계를 통해 리스코프 치환 원칙을 위반하는 예를 봤었어서 더 이해가 잘되었습니다.
특히 클라이언트의 행동 관점에서 봐야한다는게 다시금 상기 되었습니다. 코드적으로는 컴파일이 되고 동작이 되더라도. 클라이언트 입장에서 바라본 **행동** 관점에서 보는 것이 더 중요하다고 느꼈습니다.

### 토론거리 
앞서도 잠깐 나왔었던 이야기 같은데요.
Spring 에서의 DI와 상속의 관계에 대해서 이야기 해봐도 좋을 것 같습니다~

**Comment by unknownKade** [comment]
저도 이번 장에서 클라이언트 관점에서 만족 시키는 부분이 중요하게 다뤄진 내용이라고 생각합니다. 그게 어렵다면 합성을 권장해서 앞선 장에서 상속을 기피 하는 내용이 많이 나왔구나 싶었어요.
DI는 합성이라고 생각하는데 이번 장에서 나왔던, 행동 관점을 잘 고려한 구조라고 생각합니다. 오늘 다른 분들 얘기 들어보면 좋을 주제 같습니다.
이번 주도 수고 많으셨습니다.
