### ISSUE TITLE
[13주차] 서브클래싱 vs 서브타이핑

### ISSUE THREAD

**Issue by beng9re** [IDIOT-s/object-book-study#84]
### 서브클래싱? 
다른 클래스의 코드를 재사용할 목적으로 상속을 사용하는 경우를 가르키고 주로 코드를 재사용할 목적으로 한다는것에 초점 

### 서브타이핑? 
타입 계층을 구성하기위해 상속을 사용하는 경우를 가르킨다. 이때 행동호환성인 `메시지 === 퍼블릭인터페이스`을 지켜야 한다.

이번 장에서 말하고자 하는것은 대부분의 잘못된 객체설계 즉 (변경사항이 많이 생기고 캡슐화가 깨지는 상황)에서는 서브클래싱으로 설계를 했을때
많이 깨진다는 사실을 알려주고 있어요. 

저는 이번장에서 서브클래싱이 나쁘다라기보다.
올바른 서브클래싱의 목적으로 상속을 사용하려면 무엇보다 서브타이핑에서 말한 행동호환성을 고려해서 작성해야하며 
서브클래싱, 서브타이핑은 서로 보완하면서 사용해야 한다. 라고 이해를 했습니다. 

즉. 서브클래싱과 서브타이핑은 대결구도가 아니고 서로 혼용해서 써야한다. 라는것을 얻었습니다!

**Comment by unknownKade** [comment]
서브클래싱 자체가 객체 설계에 맞지 않단 얘기로 이해했었는데 제가 잘못 이해했었네요. 행동 호환성을 고려해서 적절하게 사용하면 좋겠습니다.
이번 주도 수고 많으셨습니다.
