### ISSUE TITLE
[14주차] 개념적 일관성 유지하기 

### ISSUE THREAD

**Issue by beng9re** [IDIOT-s/object-book-study#86]
이번장은 약간 종합선물세트 같은 장 이었네요. 캡슐화에 대한 종류 설명과 리펙토링 까지
결론은 `개념적 무결성` 을 지켜서 누가 오더라도 유지보수가 지속 가능한 형태로 코드를 작성해라 라는것을 의미하는 장 같았어요  
그리고, 완벽한 설계는 없으니 항상 그렇듯 지속적으로 코드를 개선하면서 맞춰 가라 라는것을 의미하는것 같았어요

### 설계의 일관성을 부여하는 방법
* 변하는 개념을 변하지 않는 개념으로 분리하자  
* 변하는 개념을 캡슐화하라. 

-> 변하는 부분을 분리해서 타입 계층을 만든다. 
-> 변하지 않는 부분의 일부로 타입 계층을 **합성**한다.

### 캡슐화의 종류 
* 데이터 캡슐화 : 클래스 내부에서 관라하는 데이터를 캡슐화 한다.
* 메서드 캡슐화 : 클래스 외부에 영향을 미치지 않고 메서드를 수정할 수 있다.
* 객체 캡슐화 : 객체 합성을 의미 
* 서브타입 캡슐화 : 서브타입의 종류를 캡슐화 하는것 -> 다형성 기반

### 개념적 무결성을 맞추는데는 어떤것들이 있을까요? 
제가 생각했을때는 코드컨벤션이나, 패키지구조를 맞추는 것도 개념적 무결성을 맞추는데도 효과가 있다고 생각이 드는데.
또 어떤것들이 있을까요?

**Comment by midcondria** [comment]
정리를 깔끔하게 해주셨군요 :thumbsup: 
좋은 코드리뷰 문화나 관리가 잘 되는 주석이 있다면 개념적 무결성을 맞추기 더 쉬워질것 같아요.
개념적 무결성을 맞추기 위해서는 결국 지속적인 관리가 필요가 필수적이지 않을까 싶습니다...

**Comment by ch200203** [comment]
Restful API 의 원칙도 개념적 무결성의 종류 중 하나가 아닐까 생각해봅니다! ㅎㅎ
그리고 프레임워크도 어떻게 보면 개념적 무결성을 위한 도구가 아닐까 싶습니다..!
