### ISSUE TITLE
[14주차] 일관성있는 협력과 코드에 대해서 생각해보기

### ISSUE THREAD

**Issue by ch200203** [IDIOT-s/object-book-study#88]
객체지향 설계의 목표는 적절한 책임을 수행하는 객체들의 협력을 기반으로 결합도가 낮고 재사용 가능한 코드 구조를 창조하는 것

객체지향 패러다임의 장점 ⇒ 설계를 재사용 할 수 있음

유사한 기능을 구현하기 위해서는 유사한 협력 패턴을 사용하는 것.

유사한 문제를 해결하는 클래스들은 설계 방식에 일관성을 가져가 주는 것이 좋다.

- 새로운 구현을 추가해야하는 상황
    - 계속해서 일관성이 어긋날 위험이 있음 그렇게 되면 아래의 문제가 더 크게 다가옴
- 기존의 구현을 이해해야 하는 상황
    - 서로 다른 구현 방식이 코드를 이해하는데 큰 방해물이 됨

유사한 요구사항을 구현하는 서로 다른 코드 구조의 코드는 코드를 이해하는 데 심리적인 장벽을 만들어 개발 하는데 더 많은 시간이 들어가게 된다.

유사한 기능은 ⇒ 유사한 방식으로 구현해야한다.

→ 레거시를 개발할 때는? 그럼 어떻게 하는것이 좋을까?

→ 오래된 소스코드를 개발할때 전체적으로 한꺼번에 변경하기 보다는 부분을 나눠 점진적으로 리팩토링해 나가는 것이 더 중요하다. 새롭게 추가되는 코드는 리팩토링과 일관성을 맞춰가는게 더 좋다고 생각!
물론 현실은 이상적이게 리팩토링할 시간이 부족할 수도 있다. 그럼에도 불구하고, 리팩토링이 전혀 불가능한 상황이 아니라면 리팩토링을 염두해두거나, 리팩토링을 점진적으로 진행해 나가면서 새로운 코드를 짜내가는 것이 더 좋다고 생각한다.

설계에 일관성을 부여하기 위해서는 다양한 설계 경험을 쌓는것 → 설계에 대한 통찰력을 쌓자.

디자인 패턴을 학습하고 변경이라는 문맥 안에서 디자인 패턴을 적용해보는 것.

디자인 패턴 = 일관성있는 설계를 만들 수 있는 경험 법칙을 모아둔 설계 템플릿.

매번 디자인 패턴이 정답을 알려주는 것은 아니기 때문에 두가지를 기억할것

- 변하는 개념을 변하지 않는 개념으로 부터 분리하기.
    - 변하는 개념을 별도의 서브타입으로 분리하고 이 서브 타입을 클라이언트로 부터 캡슐화 시킨다.
- 변하는 개념을 캡슐화 하기.
    - 추상화를 찾아 추상화에 의존하도록 만든다.
        - 의존성 관리 기법 활용
        - 타입을 캡슐화하기 위해 상속을 이용(코드 재사용을 위해 상속을 이용하지 않기.)
        - 상속 대신 합성을 이용하기
        - 리스코프 치환원칙을 준수하는 타입 계층을 구현하기 위한 상속

객체지향 소프트웨어에서는 변할 수 있는 어떤 `개념` 이라도 감추는 것이다.

캡슐화의 종류에는

- 데이터 캡슐화
- 메서드 캡슐화
- 클래스 캡슐화
- 서브타입 캡슐화

구체적인 협력 구현하기

유사한 기능에 대해 유사한 협력 패턴을 적용하는 것은 객체지향 시스템에서 `개념적 무결성(Conceptual Integrity)`을 유지할 수 있는 가장 효과적인 방법이다. 시스템이 일관성 있는 몇 개의 협력 패턴으로 구성된다면 시스템을 이해하고, 수정하고, 확장하는 데 필요한 노력과 시간을 아낄 수 있다.

`Repository 패턴`을 사용하여 데이터 액세스 로직을 분리하고, `Service 패턴을` 사용하여 비즈니스 로직을 처리하는 것도 이것의 일종이지 않을까 생각해봅니다.

**Comment by midcondria** [comment]
좋은 정리 감사합니다!
오 철환님의 말씀을 듣고 생각해보니 레디스를 쓸때 서비스 단에서 그냥 RedisTemplate를 호출해서 사용했는데
QueryDsl 쓰는것 처럼 xxxRepository 인터페이스를 구현하는 xxxRepositoryRedis 구현체로 따로 분리하면 xxxRepository만 의존하고도 사용할 수 있을것 같네요.
철환님의 좋은 정리 덕에 좋은 인사이트를 얻었습니다 ㅎㅎ
