### ISSUE TITLE
[1주차] 1장 가방에게도 책임을 주는것이 맞나요?

### ISSUE THREAD

**Issue by unknownKade** [IDIOT-s/object-book-study#9]
전 세션 전까지 서비스 계층에서 로직 다 처리하는 패러다임만 알고 있었어서, 세션에서 다뤘던 내용이 다 신선한 충격이었어요😂. 책과 다이아그램으로 차근차근 다시 보니까 객체 중심으로 설계하는 것이 어떤 것인지 왜 하는지 더 잘 이해가 되었습니다. 다시 이 내용을 자세히 접해보니, 그 간 만든 프로젝트에서 세션 때 본 것을 모방했지만 객체지향의 핵심을 다시 놓친 것 같았습니다.

제가 놓친 핵심적 내용, 앞으로 어떻게 고쳐 나갈지 생각을 좀 해본 것과 궁금한 점 올려봅니다.

### 가져가는 핵심 내용
그저 객체에서 로직을 처리하게 한다고만 생각하다보니 왜 객체에서 처리하는지를 잊고 있었습니다. 객체가 자신을 스스로를 책임지지 않게 되면 불가피하게 어딘가에 대신 그 책임이 몰리게 되고, 그 객체가 없으면 안되는 결합도가 높아져 유연성이 떨어집니다. **객체의 내부 상태를 숨기는 캡슐화**를 하고  **다른 객체와는 메시지로 소통**을 하면, 각 객체는 자율성이 높으면서도 서로에게 협력할 수 있습니다.

### 앞으로 개선할 부분
엉뚱하겠지만 1장 보고 앞으로 설계 할 때 클래스 다이아그램에 노력을 기울여야겠다는 생각이 들었습니다. 그 전까지는 클래스 다이아그램은 코드 봐도 빨리 파악 할 수 있는데 만드는데 오래 걸리는 번거로운 다이아그램이라고만생각했는데, 그건 책임이 중앙집중 되어서 그랬던 것이었습니다. 아직 객체지향적으로 보는 게 미숙한 단계에서는 **다이어그램으로 책임과 의존성이 어디있는지 파악하고 만들어가는게 좋다**고 생각합니다.

### 궁금점
p30에서 bag이 수동적인 객체이기 때문에 책임을 줬는데 이게 저로 하여금 DTO, VO 같은 데이터 운반의 역할을 갖는 객체에 대해 생각하게끔했습니다. 예시에서는 가방도 일종의 도메인처럼 나오지만 실제로 가방은 물건을 보관하는 곳일 뿐인데 가방의 자율성을 확보하고 책임을 줘서 사람이 요구할 때 물건을 꺼내다 주는 행동을 하는 능동적 객체로 만들어서 데이터만 보관하는 객체에도 이렇게 책임을 주는 것이 맞는지 의문입니다. 나아가서 그렇다면 최신 자바에 추가된, 무조건 getter,setter가있는 record에 대해서 어떻게 생각하시는지 궁금합니다.

**Comment by platanus-kr** [comment]
금주도 수고 많으셨습니다.
저도 처음엔 컨트롤러-서비스-레포지토리 형태의 비즈니스 처리만 생각하다가 '객체' 에서 무언가를 한다는 사실을 알게 된지 얼마 안됐어요.
이 방식대로 코드를 짜보면 도메인이 더 명확해지는 장점이 있는것 같습니다.

질문에 대한 답변을 드리자면..
객체간 메시지를 전달하기 위한 DTO(VO포함)에 적용되는 내용은 아닌것으로 보이구요. 제 생각엔 실제 비즈니스를 자율적으로 처리하는 객체에 더 중점을 두고 '어떻게 객체 내 메소드 내용을 정리해서 객체가 의미있는 행동을 가지게 하는가'에 대한 내용이였다고 봐요.
record는 제가봤을땐 최근 자바 기조를 봤을때 '좋은 것은 모두 내꺼' 라는 취지에서 코틀린의 data 클래스에서 영향을 받았다고 봅니다 😂

**Comment by platanus-kr** [comment]
@zinzoddari  우리가 스프링 기반에서 계속 개발을 해서 그렇게만 생각을 하고 있는게 아닐까요? 
@beng9re  DTO는 레이어간 전달하는 객체, 레이어간 전달을 위한 클래스는 record 선호 / DTO는 로직을 가질 수 없지만 VO는 로직을 가질 수 있다. DDD관점의 내용.
