### ISSUE TITLE
[15장] 간단한 정리와 후기

### ISSUE THREAD

**Issue by ch200203** [IDIOT-s/object-book-study#90]
## 디자인 패턴이란?

- 소프트 웨어 설계에서 반복적으로 발생하는 문제에 대해 적용할 수 있는 방법
- 디자인 패턴을 바탕으로 `변경의 방향`과 `주기`를 이해 하는 것 만으로도 필용한 역할과 책임 그리고 협력 방식을 적용할 수 있다.

## 프레임워크

- 설계와 코드를 함께 재사용하기 위한것
- 어플리케이션의 아키텍처를 구현 코드의 형태로 제공
- **일관성** 있게 다를 수 있는 확장 가능한 **코드 템플릿**을 제공

### 패턴은 경험의 산물

- 실무 경험이 적은 초보자라고 하더라고 패턴을 익히고 반복적으로 적용하는 과정 속에서 유연하고 품질 높은 소프트웨어를 개발하는 방법을 익힐 수 있게 된다.

### 디자인패턴

- 특정 상황 내에서 일반적인 설계 문제를 해결하며 협력하는 컴포넌트들 사이에서 반복적으로 발생하는 구조를 서술한다
- 특정한 설계문제를 해결하는 것을 목적으로 함
- 프로그래밍 언어나 패러다임에 독립적이다
- 

### 자세한 디자인패턴 참고

[https://i-am-your-father.notion.site/Gang-of-Four-4e354fd5da844a56ace1e8454f39894b](https://www.notion.so/4e354fd5da844a56ace1e8454f39894b?pvs=21)

패턴만능주의를 경계하자.

모든 문제를 디자인 패턴으로 해결하려 하다보면 `부작용`을 낳기 쉬워진다.
패턴을 남용하지 않기 위해서는 다양한 `트레이드 오프`관계 속에서 패턴을 적용하고 사용해야 합니다.

---

아직은 프로그램을 설계단계에서 00패턴을 써서 설계해야지와 같은 생각은 아직 잘 들지 않더라구요. 의도적으로 적용해보려고하면 적용과정에서도 막히는 부분이 많아서 아직은 저한테는 익숙하지 않은 부분인건 같아요. 반면에 리팩토링이나 코드를 짜다 보면 어? 이부분은 이런 패턴을 적용하면 좋겠다. 

혹은 추상화나 객체지향적인 코드를 짤려고 노력하다 보면 어 이거 생각해보니 00패턴이랑 비슷한데? 하는 경우가 있는 것 같습니다.

앞으로 공부해야할 부분이 참 많은 것 같습니다… 패턴을 실무에서 적용하는 과정에 책에서 말하는 것처럼 쉬운 행위는 아니더라구

책일 읽으면서 최근 짜는 코드에 대해서도 몇가지 변화가 생겼습니다. 한가지는 끊임없이 객체지향적인 코드인지 계속 의문을 던져보고, 제가 짜는 코드에 트레이드 오프에 대해서 생각해보고 있습니다. 

덕분에 짜는 속도도 느리고, 이게 정말 맞는 코드인지 계속 고민이 되어 생산성이 낮아지는 경험을 하고 있습니다.ㅎㅎㅎ

다들 1장부터 15장까지 긴 시간동안 함께해주시느라 너무 고생많으셨습니다~~

--- 

마지막 질문!

책을 읽은 후 여러분들의 코드는 변화가 있으셨을까요? 
혹은 여러분들이 생각하는 객체지향이란 무엇일까요?

**Comment by beng9re** [comment]
고생하셨습니다!
